In [10]:
# Code to filter maven data elements that have a corresponding cste and mmg elements
# Out of 9501 there are 157 mmg and 156 cste matching elements
# and 15 that are common between mmg and cste
# There are 298 unique maven elements that have a corresponding mmg and cste elements

In [11]:
import pandas as pd

In [12]:
# To help with some elements common to mmg and cste

df_maven = pd.read_csv('output/maven_all_with_mmg_and_cste.csv',na_filter=False)
len(df_maven)

9501

In [13]:
df_maven_sub = df_maven[(df_maven['Question.Package.ID']=='DEMOGRAPHIC')|(df_maven['Question.Package.ID']=='ADMINISTRATIVE')]

In [14]:
len(df_maven_sub)

457

In [15]:
# Counting non-empty mmg and cste elements
df_maven_sub = df_maven[(df_maven['mmg_element']!='')|(df_maven['cste_element']!='')]
len(df_maven_sub)

298

In [16]:
df_maven_sub

,Model,question_number,depth,Question,Question.Package.ID,Question.Package.Name,Message,mmg_element,cste_element
40,General,41,3,DATE_SENT_TO_CDC,ADMINISTRATIVE,Administrative,>>> Date sent to CDC,Date of Electronic Case Notification to CDC,
63,General,64,0,IMPORTED_DISEASE,ADMINISTRATIVE,Administrative,Was the case locally acquired or imported into...,Case Disease Imported Code,
64,General,65,0,IMPORTED_DISEASE_CITY,ADMINISTRATIVE,Administrative,Imported city,Imported City,
65,General,66,0,IMPORTED_DISEASE_STATE,ADMINISTRATIVE,Administrative,Imported state,Imported State,
66,General,67,0,IMPORTED_DISEASE_COUNTY,ADMINISTRATIVE,Administrative,Imported county,Imported County,
...,...,...,...,...,...,...,...,...,...
9307,STD,2232,1,CDR_SYMPTOMS_CLINICIAN_OBS_DATE,,,,,Clinical Manifestations
9308,STD,2233,1,CDR_SYMPTOMS_PATIENT_DESCRIBED,,,,,Clinical Manifestations
9309,STD,2234,1,CDR_SYMPTOMS_PATIENT_DESCRIBED_DATE,,,,,Clinical Manifestations
9310,STD,2235,1,CDR_SYMPTOMS_DURATION,,,,,Clinical Manifestations
9448,STD,2373,0,SYMPTOMS_INV,,,,,Clinical Manifestations

In [17]:
df_maven_sub[['Model','question_number','Question','Question.Package.ID','mmg_element','cste_element']].to_csv('output/maven_mmg_cste_elements_only.csv',index=False)

In [ ]:
# Other metrics

In [5]:
df_maven.columns

Index(['Model', 'question_number', 'depth', 'Question', 'Question.Package.ID',
       'Question.Package.Name', 'Message', 'mmg_element', 'cste_element'],
      dtype='object')

In [6]:
df_mmg = df_maven[df_maven['mmg_element']!='']
len(df_mmg)

157

In [7]:
df_cste = df_maven[df_maven['cste_element']!='']
len(df_cste)

156

In [9]:
df_merge = pd.merge(df_mmg,df_cste,on='Question')
len(df_merge)

39

In [10]:
df_merge

,Model_x,question_number_x,depth_x,Question,Question.Package.ID_x,Question.Package.Name_x,Message_x,mmg_element_x,cste_element_x,Model_y,question_number_y,depth_y,Question.Package.ID_y,Question.Package.Name_y,Message_y,mmg_element_y,cste_element_y
0,General,342,0,DEATH_DATE,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death,General,342,0,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death
1,General,342,0,DEATH_DATE,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death,Coinfection,4,0,,,Date of death,Deceased Date,Date of Death
2,General,342,0,DEATH_DATE,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death,Hepatitis,212,0,,,,Deceased Date,Date of Death
3,General,342,0,DEATH_DATE,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death,STD,9,0,,,,Deceased Date,Date of Death
4,General,1100,0,PREGNANCY_STATUS,CLINICAL,Clinical,Pregnant at time of report?,Pregnancy Status,Pregnancy Status,General,1100,0,CLINICAL,Clinical,Pregnant at time of report?,Pregnancy Status,Pregnancy Status
5,General,1172,1,HOSPITAL_ADMISSION_DATE,CLINICAL,Clinical,> Date admitted,Admission Date,Admission Date,General,1172,1,CLINICAL,Clinical,> Date admitted,Admission Date,Admission Date
6,General,1172,1,HOSPITAL_ADMISSION_DATE,CLINICAL,Clinical,> Date admitted,Admission Date,Admission Date,Hepatitis,393,0,,,,Admission Date,Admission Date
7,General,1192,1,HOSPITAL_DISCHARGE_DATE,CLINICAL,Clinical,> Date discharged,Discharge Date,Discharge Date,General,1192,1,CLINICAL,Clinical,> Date discharged,Discharge Date,Discharge Date
8,General,1192,1,HOSPITAL_DISCHARGE_DATE,CLINICAL,Clinical,> Date discharged,Discharge Date,Discharge Date,Hepatitis,394,0,,,,Discharge Date,Discharge Date
9,Childhood Lead,472,0,DECEASED,,,,Subject Died,Person Deceased,Childhood Lead,472,0,,,,Subject Died,Person Deceased
10,Coinfection,1,0,SEX_BIRTH,,,Sex at birth,Subjects Sex,Sex,Coinfection,1,0,,,Sex at birth,Subjects Sex,Sex
11,Coinfection,1,0,SEX_BIRTH,,,Sex at birth,Subjects Sex,Sex,STD EHR and screening,8,0,,,Sex at birth,Subjects Sex,Sex
12,Coinfection,1,0,SEX_BIRTH,,,Sex at birth,Subjects Sex,Sex,STD,5,0,SURRG_WIZARD,SURRG Wizard,Sex at birth,Subjects Sex,Sex
13,Coinfection,4,0,DEATH_DATE,,,Date of death,Deceased Date,Date of Death,General,342,0,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death
14,Coinfection,4,0,DEATH_DATE,,,Date of death,Deceased Date,Date of Death,Coinfection,4,0,,,Date of death,Deceased Date,Date of Death
15,Coinfection,4,0,DEATH_DATE,,,Date of death,Deceased Date,Date of Death,Hepatitis,212,0,,,,Deceased Date,Date of Death
16,Coinfection,4,0,DEATH_DATE,,,Date of death,Deceased Date,Date of Death,STD,9,0,,,,Deceased Date,Date of Death
17,Coinfection,471,1,CASE_HOSPITALIZED,,,Patient hospitalized,Hospitalized,Hospitalized,Coinfection,471,1,,,Patient hospitalized,Hospitalized,Hospitalized
18,Coinfection,471,1,CASE_HOSPITALIZED,,,Patient hospitalized,Hospitalized,Hospitalized,STD,1045,1,,,,Hospitalized,Hospitalized
19,STD EHR and screening,8,0,SEX_BIRTH,,,Sex at birth,Subjects Sex,Sex,Coinfection,1,0,,,Sex at birth,Subjects Sex,Sex
20,STD EHR and screening,8,0,SEX_BIRTH,,,Sex at birth,Subjects Sex,Sex,STD EHR and screening,8,0,,,Sex at birth,Subjects Sex,Sex
21,STD EHR and screening,8,0,SEX_BIRTH,,,Sex at birth,Subjects Sex,Sex,STD,5,0,SURRG_WIZARD,SURRG Wizard,Sex at birth,Subjects Sex,Sex
22,Hepatitis,212,0,DEATH_DATE,,,,Deceased Date,Date of Death,General,342,0,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death
23,Hepatitis,212,0,DEATH_DATE,,,,Deceased Date,Date of Death,Coinfection,4,0,,,Date of death,Deceased Date,Date of Death
24,Hepatitis,212,0,DEATH_DATE,,,,Deceased Date,Date of Death,Hepatitis,212,0,,,,Deceased Date,Date of Death
25,Hepatitis,212,0,DEATH_DATE,,,,Deceased Date,Date of Death,STD,9,0,,,,Deceased Date,Date of Death
26,Hepatitis,393,0,HOSPITAL_ADMISSION_DATE,,,,Admission Date,Admission Date,General,1172,1,CLINICAL,Clinical,> Date admitted,Admission Date,Admission Date
27,Hepatitis,393,0,HOSPITAL_ADMISSION_DATE,,,,Admission Date,Admission Date,Hepatitis,393,0,,,,Admission Date,Admission Date
28,Hepatitis,394,0,HOSPITAL_DISCHARGE_DATE,,,,Discharge Date,Discharge Date,General,1192,1,CLINICAL,Clinical,> Date discharged,Discharge Date,Discharge Date
29,Hepatitis,394,0,HOSPITAL_DISCHARGE_DATE,,,,Discharge Date,Discharge Date,Hepatitis,394,0,,,,Discharge Date,Discharge Date
30,STD,5,0,SEX_BIRTH,SURRG_WIZARD,SURRG Wizard,Sex at birth,Subjects Sex,Sex,Coinfection,1,0,,,Sex at birth,Subjects Sex,Sex
31,STD,5,0,SEX_BIRTH,SURRG_WIZARD,SURRG Wizard,Sex at birth,Subjects Sex,Sex,STD EHR and screening,8,0,,,Sex at birth,Subjects Sex,Sex
32,STD,5,0,SEX_BIRTH,SURRG_WIZARD,SURRG Wizard,Sex at birth,Subjects Sex,Sex,STD,5,0,SURRG_WIZARD,SURRG Wizard,Sex at birth,Subjects Sex,Sex
33,STD,9,0,DEATH_DATE,,,,Deceased Date,Date of Death,General,342,0,DEMOGRAPHIC,Demographic,Date of death,Deceased Date,Date of Death
34,STD,9,0,DEATH_DATE,,,,Deceased Date,Date of Death,Coinfection,4,0,,,Date of death,Deceased Date,Date of Death
35,STD,9,0,DEATH_DATE,,,,Deceased Date,Date of Death,Hepatitis,212,0,,,,Deceased Date,Date of Death
36,STD,9,0,DEATH_DATE,,,,Deceased Date,Date of Death,STD,9,0,,,,Deceased Date,Date of Death
37,STD,1045,1,CASE_HOSPITALIZED,,,,Hospitalized,Hospitalized,Coinfection,471,1,,,Patient hospitalized,Hospitalized,Hospitalized
38,STD,1045,1,CASE_HOSPITALIZED,,,,Hospitalized,Hospitalized,STD,1045,1,,,,Hospitalized,Hospitalized