In [1]:
import pandas as pd
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

In [5]:
df_maven = pd.read_csv('maven_disease_vars_ALL_MODELS_2025-08-05.csv',na_filter=False)
len(df_maven)

9833

In [7]:
# Goal is to find duplicates between the three data sources - Maven, MMG and CSTE
df_maven_only = df_maven[df_maven['Source']=='Maven']
len(df_maven_only)

9486

In [13]:
df_maven_only

,Source,Model,question_number,depth,Question - Maven Data Element,Question.Package.ID,Question.Package.Name,Message,MMG Data Element Name,MMG\nCSTE Data Element,CSTE\nGenV2 (MMG),CSTE\nMMG Data Element Name,CSTE\nMaven MODEL Inclusion Determ,CSTE Data Element,CSTE Value Set,CSTE Values
0,Maven,Lead investigation,211,0,ABATEMENT,,,Does this property require an abatement?,,,,,,,,
1,Maven,Lead investigation,212,1,ABATEMENT_DATE,,,Date Lead Abatement Order issued:,,,,,,,,
2,Maven,Lead investigation,213,1,ABATEMENT_DATE_RECEIVED,,,Date Lead Abatement Plan received:,,,,,,,,
3,Maven,Lead investigation,214,1,ABATEMENT_DATE_REVIEWED_1,,,Date Lead Abatement Plan reviewed and notifica...,,,,,,,,
4,Maven,Lead investigation,216,1,ABATEMENT_DATE_REVIEWED_2,,,Date Lead Abatement Plan reviewed and notifica...,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9534,Maven,Hepatitis,220,0,ZIP,,,,,,,,,,,
9536,Maven,Childhood Lead,470,0,ZIP_CODE,,,,,,,,,,,
9537,Maven,Coinfection,114,0,ZIP_CODE,,,Zip code,,,,,,,,
9538,Maven,STD,161,0,ZIP_CODE,,,,,,,,,,,
9539,Maven,STD EHR and screening,14,0,ZIP_CODE,,,Zipcode,,,,,,,,

In [8]:
df_mmg = df_maven[df_maven['Source']=='MMG']
len(df_mmg)

65

In [ ]:
df_mmg

,Source,Model,question_number,depth,Question - Maven Data Element,Question.Package.ID,Question.Package.Name,Message,MMG Data Element Name,MMG\nCSTE Data Element,CSTE\nGenV2 (MMG),CSTE\nMMG Data Element Name,CSTE\nMaven MODEL Inclusion Determ,CSTE Data Element,CSTE Value Set,CSTE Values
540,MMG,Subject Related,,,BIRTH_DATE,DEMOGRAPHIC,,Patient’s date of birth,Birth Date,,,,,,,
734,MMG,Case Related,,,CASE_REPORT_DATE,ADMINISTRATIVE,,Date that a health department first suspected ...,Date Reported,,,,,,,
757,MMG,Case Related,,,CDC_CALL_DATE,ADMINISTRATIVE,,Date the case of an Immediately National Notif...,Date CDC Was First Verbally Notified of This Case,,,,,,,
2070,MMG,Subject Related,,,COUNTRY,DEMOGRAPHIC,,Where does the person usually live (defined as...,Country of Usual Residence,,,,,,,
2075,MMG,Subject Related,,,COUNTRY_OF_BIRTH,DEMOGRAPHIC,,Country of Birth,Country of Birth,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,MMG,Case Related,,,,RHAPSODY,,Identifier for the physical site from which th...,Jurisdiction Code,,,,,,,
9547,MMG,Case Related,,,,,,"For cases meeting the binational criteria, sel...",Binational Reporting Criteria,,,,,,,
9548,MMG,Case Related,,,,RHAPSODY,,Email Address of the person reporting the case...,Person Reporting to CDC - Email,,,,,,,
9549,MMG,Case Related,,,,,,County reporting the notification,Reporting County,,,,,,,
9550,MMG,Case Related,,,,,,"Use this field, if needed, to communicate anyt...",Comment,,,,,,,

In [14]:
# Compare the data elements in df_maven_only and df_mmg

# Using fuzz.token_set_ratio() - ignores duplicate words and order
df_mmg.loc[:,'score'] = [fuzz.token_set_ratio(mmg,maven) for (mmg,maven) in zip(df_mmg.loc[:,'MMG Data Element Name'],df_mmg.loc[:,'Question - Maven Data Element'])]

C:\Users\s.chintabathina\AppData\Local\Temp\ipykernel_26704\914520850.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mmg.loc[:,'score'] = [fuzz.token_set_ratio(mmg,maven) for (mmg,maven) in zip(df_mmg.loc[:,'MMG Data Element Name'],df_mmg.loc[:,'Question - Maven Data Element'])]

In [17]:
df_mmg[['Question - Maven Data Element','MMG Data Element Name','score']].to_csv('compare_maven_mmg.csv',index=False)

In [16]:
df_mmg

,Source,Model,question_number,depth,Question - Maven Data Element,Question.Package.ID,Question.Package.Name,Message,MMG Data Element Name,MMG\nCSTE Data Element,CSTE\nGenV2 (MMG),CSTE\nMMG Data Element Name,CSTE\nMaven MODEL Inclusion Determ,CSTE Data Element,CSTE Value Set,CSTE Values,score
540,MMG,Subject Related,,,BIRTH_DATE,DEMOGRAPHIC,,Patient’s date of birth,Birth Date,,,,,,,,90
734,MMG,Case Related,,,CASE_REPORT_DATE,ADMINISTRATIVE,,Date that a health department first suspected ...,Date Reported,,,,,,,,62
757,MMG,Case Related,,,CDC_CALL_DATE,ADMINISTRATIVE,,Date the case of an Immediately National Notif...,Date CDC Was First Verbally Notified of This Case,,,,,,,,23
2070,MMG,Subject Related,,,COUNTRY,DEMOGRAPHIC,,Where does the person usually live (defined as...,Country of Usual Residence,,,,,,,,100
2075,MMG,Subject Related,,,COUNTRY_OF_BIRTH,DEMOGRAPHIC,,Country of Birth,Country of Birth,,,,,,,,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,MMG,Case Related,,,,RHAPSODY,,Identifier for the physical site from which th...,Jurisdiction Code,,,,,,,,0
9547,MMG,Case Related,,,,,,"For cases meeting the binational criteria, sel...",Binational Reporting Criteria,,,,,,,,0
9548,MMG,Case Related,,,,RHAPSODY,,Email Address of the person reporting the case...,Person Reporting to CDC - Email,,,,,,,,0
9549,MMG,Case Related,,,,,,County reporting the notification,Reporting County,,,,,,,,0
9550,MMG,Case Related,,,,,,"Use this field, if needed, to communicate anyt...",Comment,,,,,,,,0

In [9]:
df_cste = df_maven[df_maven['Source']=='CSTE']
len(df_cste)

282

In [12]:
df_cste

,Source,Model,question_number,depth,Question - Maven Data Element,Question.Package.ID,Question.Package.Name,Message,MMG Data Element Name,MMG\nCSTE Data Element,CSTE\nGenV2 (MMG),CSTE\nMMG Data Element Name,CSTE\nMaven MODEL Inclusion Determ,CSTE Data Element,CSTE Value Set,CSTE Values
9551,CSTE,,,,,,,,,,,,YES,Sexual Orientation,Sexual Orientation,Asexual
9552,CSTE,,,,,,,,,,,,YES,Sexual Orientation,Sexual Orientation,Bisexual
9553,CSTE,,,,,,,,,,,,YES,Sexual Orientation,Sexual Orientation,"Lesbian, gay, or same-gender loving"
9554,CSTE,,,,,,,,,,,,NO,Sexual Orientation,Sexual Orientation,Pansexual
9555,CSTE,,,,,,,,,,,,NO,Sexual Orientation,Sexual Orientation,Queer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9828,CSTE,,,,,,,,,,,,NO,Reason(s) for Travel,Travel Purpose (CDC),Tourism
9829,CSTE,,,,,,,,,,,,NO,Reason(s) for Travel,Travel Purpose (CDC),Unknown
9830,CSTE,,,,,,,,,,,,NO,Reason(s) for Travel,Travel Purpose (CDC),Visiting friends/relatives
9831,CSTE,,,,,,,,,,,,YES,Date of Arrival to Travel Destination,N/A - Date,N/A - Date
9832,CSTE,,,,,,,,,,,,YES,Date of Departure from Travel Destination,N/A - Date,N/A - Date

In [18]:
# Compare the data elements in df_maven_only and df_mmg

# Using fuzz.token_set_ratio() - ignores duplicate words and order
df_cste.loc[:,'score'] = [fuzz.token_set_ratio(cste,maven) for (cste,maven) in zip(df_cste.loc[:,'CSTE Data Element'],df_cste.loc[:,'Question - Maven Data Element'])]

C:\Users\s.chintabathina\AppData\Local\Temp\ipykernel_26704\1899382478.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cste.loc[:,'score'] = [fuzz.token_set_ratio(cste,maven) for (cste,maven) in zip(df_cste.loc[:,'CSTE Data Element'],df_cste.loc[:,'Question - Maven Data Element'])]

In [19]:
df_cste[['Question - Maven Data Element','CSTE Data Element','score']].to_csv('compare_maven_cste.csv',index=False)

In [10]:
df_cste.columns

Index(['Source', 'Model', 'question_number', 'depth',
       'Question - Maven Data Element', 'Question.Package.ID',
       'Question.Package.Name', 'Message', 'MMG Data Element Name',
       'MMG\nCSTE Data Element', 'CSTE\nGenV2 (MMG)',
       'CSTE\nMMG Data Element Name', 'CSTE\nMaven MODEL Inclusion Determ',
       'CSTE Data Element', 'CSTE Value Set', 'CSTE Values'],
      dtype='object')

In [ ]:
# Find duplicates in Question - Maven Data Element