In [ ]:
# Code to map Maven Lead elements to Origami Lead elements
# Using semantic similarity library
# Author: Sandeep Chintabathina
# March 2026

In [ ]:
# For each Maven Lead data element, check if there is an exact or close matching data element in the origami Lead package
# The output will list the maven element alongside the origami element and other supporting attributes

In [230]:
from sentence_transformers import SentenceTransformer

In [231]:
import pandas as pd
import numpy as np

In [232]:
# Read maven elements
df_maven = pd.read_csv('output/maven_all_with_mmg_and_cste.csv',na_filter=False)
len(df_maven)

9501

In [233]:
df_maven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9501 entries, 0 to 9500
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Model                  9501 non-null   object
 1   question_number        9501 non-null   int64
 2   depth                  9501 non-null   int64
 3   Question               9501 non-null   object
 4   Question.Package.ID    9501 non-null   object
 5   Question.Package.Name  9501 non-null   object
 6   Message                9501 non-null   object
 7   mmg_element            9501 non-null   object
 8   cste_element           9501 non-null   object
dtypes: int64(2), object(7)
memory usage: 668.2+ KB

In [234]:
def clean_up(name):
    new_name =''
    for ch in name:
        # If not space, digits, uppercase letters, lowercase letters, or underscore, ignore it
        if not (ord(ch)==32 or 48<=ord(ch)<=57 or 65<=ord(ch)<=90 or 97<=ord(ch)<=122 or ord(ch)==95 ):
            new_name+=''
        else:
            new_name+=ch
    return new_name.strip()

In [ ]:
# Clean up questions or data elements
df_maven.loc[:,'Question'] =[ clean_up(q) for q in df_maven.loc[:,'Question']]

In [236]:
df_maven.loc[:,'Model'].value_counts(dropna=False)

Model
General                  3866
STD                      2425
Coinfection               923
Hepatitis                 901
Childhood Lead            606
Cluster                   425
Lead investigation        255
STD EHR and screening      85
Aggregate                  15
Name: count, dtype: int64

In [237]:
df_maven_lead = df_maven[df_maven['Model']=='Childhood Lead']
len(df_maven_lead)

606

In [238]:
# No duplicates
df_maven_lead[df_maven_lead.duplicated(['Question'],keep=False)]

Empty DataFrame
Columns: [Model, question_number, depth, Question, Question.Package.ID, Question.Package.Name, Message, mmg_element, cste_element]
Index: []

In [239]:
# Read origami elements
df_origami = pd.read_csv('origami/Custom__CaseLead.csv',na_filter=False)
len(df_origami)

783

In [240]:
df_origami.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783 entries, 0 to 782
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Field                 783 non-null    object
 1   Type                  783 non-null    object
 2   Label                 783 non-null    object
 3   Required in Database  783 non-null    bool
 4   Can't Protect         783 non-null    bool
 5   FK Table              783 non-null    object
 6   CodeTypeID            783 non-null    object
 7   Static Codes          783 non-null    object
 8   Field Notes           783 non-null    object
 9   Global Comments       783 non-null    object
 10  Local Comments        783 non-null    object
dtypes: bool(2), object(9)
memory usage: 56.7+ KB

In [241]:
df_origami.loc[:,'Label'].value_counts(dropna=False)

Label
                                       382
HI_lead_18                               2
HI_lead_26                               2
Have they all been tested for lead?      2
HI_lead_8                                2
                                      ...
HG_EXP_BROKEN_ITEM                       1
HG_EXP_EMISSIONS                         1
HG_EXP_PRODUCT                           1
HG_EXP_JOB_ACTIVITY                      1
HI_lead_13_details                       1
Name: count, Length: 398, dtype: int64

In [242]:
# Get the two columns of interest and non-blank values
df_origami = df_origami[['Field','Label']]
df_origami = df_origami[df_origami['Label']!='']
len(df_origami)

401

In [243]:
df_origami = df_origami.reset_index(drop=True)

In [244]:
# Original label to be used later for output
original_labels = list(df_origami.Label)
original_labels

['Case Lead ID',
 'Client',
 'Entry User',
 'Entry Date',
 'Modified User',
 'Modified Date',
 'IncidentID',
 '[lead_preg_blt]If pregnant, was blood lead testing',
 '[lead_under16]Is this a Child Case (<16 yrs) or Ad',
 '[lead_bl_specsource]Specimen Source',
 '[lead_above_3.5]Test result at or above 3.5 µg/dL',
 '[lead_bl_reas_testing]Reason for testing',
 '[lead_performing_lab_type]Performing lab type',
 '[lead_bl_test_funding]Test source of funding',
 '[lead_medicaid]Medicaid',
 '[lead_chelated]Chelation therapy administered',
 '[lead_chelate_type]Chelated type',
 '[lead_chel_fund]Source of funding for the chelatio',
 '[lead_dev_assessment]Developmental assessment cond',
 '[lead_household_lead]We they tested for lead',
 '[21522001]Abdominal Pain or Tenderness',
 '[86276007]Bleeding gums',
 '[14760008]Constipation',
 '[84229001]Fatigue',
 '[25064002]Headache',
 '[422400008]Vomiting',
 '[721294001]Hearing loss',
 '[163028000]High blood pressure',
 '[79890006]Loss of appetite',
 '[91175000]Seizures',
 '[89362005]Weight loss',
 '[local_oth]Other',
 '[lead_adult_lead_industry]Do any teenages or adult',
 '[lead_adult_lead_industry_blood]Blood tested',
 '[lead_adult_lead_industry_clothing]Are clothes cha',
 '[lead_adult_industry_shower]Do they shower at work',
 '[lead_adult_lead_industry_hands]Do they wash hands',
 '[lead_adult_lead_industry_wclothes]Do they wash wo',
 '[lead_hobby]Does anyone in the home have a hobby i',
 '[lead_chew_nonfood]Does the child eat or chew on n',
 '[lead_dirt]Does the child eat dirt',
 '[lead_res_county]County',
 '[lead_address_type]Address type',
 '[lead_home_type]Type of Residence',
 '[lead_owner_type]Ownership',
 '[lead_current_address]Current Address',
 '[owner_type]Residential ownership status',
 '[lead_dwell_type]Type of dwelling',
 '[lead_paint_haz]Dwelling with peeling, chipping, o',
 '[lead_indhaz]Industrial hazard near dwelling',
 '[lead_pa_hazzard]Lead hazard',
 '[lead_clearance_per]Clearance performed',
 '[lead_clear_rslt]Clearance testing results',
 'ISLAND',
 'HEAVY_METALS',
 'WORK_RELATED_EXP',
 'AS_EXP_JOB_ACTIVITY',
 '[lead_home_addtl_cmmnts]Additional Comments',
 'HI_lead_6',
 'HI_lead_10',
 'HI_lead_11',
 'HI_lead_15',
 '[lead_accession]Accession Number',
 '[lead_bloodresult]Result measured in µg/dL',
 '[lead_bl_reas_tes_oth]Other reason',
 '[lead_medicaid_num]Medicaid ID Number',
 '[lead_6hr_location]Name of Location',
 '[lead_6hr_address]Address',
 '[lead_6_hr_phone]Phone',
 '[lead_6hr_spent_at_other]Average time spent at thi',
 '[lead_household_name]Name',
 '[lead_household_relationship]Relationship to subje',
 '[symp_oth_details]Specify other symptoms',
 '[lead_adult_lead_industry_name]Name',
 '[lead_adult_lead_industry_occ]Occupation',
 '[lead_adult_lead_industry_wp]Work place',
 '[lead_adult_lead_industry_length]Length at occupat',
 '[lead_res_address]Address',
 '[lead_res_city]City',
 '[lead_6hr_zip]Zip Code',
 '[lead_address_type_oth]Other address type',
 '[lead_owner_other]Please Specify',
 '[lead_build_year]Year Built',
 '[lead_frst_dt]Moved-in Date',
 '[lead_dwell_type_oth]Specify other',
 'COMP_NAME',
 'AS_WATER_SOURCE_OTH',
 '[report_date]Report Date',
 '[33882_2]Specimen Collection Date',
 '[lead_res_dt]Result Date',
 '[lead_dev_assessment_dt]Date completed',
 '[lead_household_dob]Date of birth',
 '[lead_moved_out_dt]Moved-out Date',
 '[lead_date_ref]Date address referred for investiga',
 '[lead_dt_first_occupied]Date first occupied',
 '[lead_dt_last_occupied]Date last occupied',
 '[lead_date_referred]Date Referred',
 '[lead_insp_comp]Date address investigation inspect',
 '[lead_date_due]Date remediation due',
 '[lead_clear_date]Date clearance testing completed',
 '[lead_addhist_dt_completed]Investigation Completed',
 '[lead_abat_comp]Date address hazard remediation or',
 '[lead_case_complete_dt]Investigation Completed',
 'HG_SWITCH_DATE',
 'HG_OTHER_DATE',
 'HG_BP_GAUGE_DATE',
 'HG_BARO_DATE',
 '[lead_xrf]Highest XRF reading in mg/cm2. (000.0)',
 '[lead_dust_sill]Highest window sill dust sample re',
 '[lead_dust_well]Highest window well dust sample re',
 '[lead_paint]Highest paint chip sample reading. (00',
 '[lead_soil]Highest soil sample reading in ppm. (00',
 '[lead_water]Highest water sample reading in ppb. (',
 'HG_FILLING_RECENT_NUM',
 'SS_FEVER_HIGHEST_TEMP',
 'Blood Lead Level',
 'lead_dust_floor',
 'Case Type',
 'AS_EXP_OTH',
 'AS_WATER_SOURCE',
 'AS_WATER_LOCATION',
 'CD_EXP_JOB_ACTIVITY',
 'CD_MEAT_SOURCE',
 'HG_EXP_FOOD_SOURCE',
 'HG_FISH_LOC',
 'HG_FISH_TYPE',
 'HG_FISH_FREQ',
 'HG_EXP_JOB_ACTIVITY',
 'HG_EXP_PRODUCT',
 'HG_EXP_EMISSIONS',
 'HG_EXP_BROKEN_ITEM',
 'HG_COSMETIC',
 'HG_WORK_SITE',
 'HG_FILLING',
 'HG_FILLING_REPAIR',
 'HG_FILLING_RECENT',
 'HG_FILLING_REMOVE',
 'PATIENT_SYMPTOMATIC',
 'SS_FEVER',
 'SS_FEVER_HIGHEST_TEMP_SCALE',
 'SS_HEADACHE',
 'SS_MALAISE',
 'SS_FATIGUE',
 'SS_ABDOMINAL_PAIN',
 'SS_NAUSEA',
 'SS_VOMITING',
 'SS_ANOREXIA',
 'SS_DARK_URINE',
 'SS_DIARRHEA',
 'SS_JAUNDICE',
 'SS_OTHER',
 'Date Type',
 'Did the patient die from this illness',
 'SCHOOL_READINESS_READING',
 'SCHOOL_READINESS_MEDIA',
 'SCHOOL_READINESS_DEVELOPMENT',
 'SCHOOL_READINESS_BASIC_NEEDS',
 'DEVELOPMENTAL_SCREENING_ZERO_TWO_COMMUNICATION',
 'DEVELOPMENTAL_SCREENING_ZERO_TWO_GROSS_MOTOR',
 'DEVELOPMENTAL_SCREENING_ZERO_TWO_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_ZERO_TWO_PROBLEM',
 'DEVELOPMENTAL_SCREENING_ZERO_TWO_PERSONAL',
 'DEVELOPMENTAL_SCREENING_TWO_FOUR_COMMUNICATION',
 'DEVELOPMENTAL_SCREENING_TWO_FOUR_GROSS_MOTOR',
 'DEVELOPMENTAL_SCREENING_TWO_FOUR_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_TWO_FOUR_PROBLEM',
 'DEVELOPMENTAL_SCREENING_TWO_FOUR_PERSONAL',
 'DEVELOPMENTAL_SCREENING_FOUR_EIGHT_COMMUNICATION',
 'DEVELOPMENTAL_SCREENING_FOUR_EIGHT_GROSS_MOTOR',
 'DEVELOPMENTAL_SCREENING_FOUR_EIGHT_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_FOUR_EIGHT_PROBLEM',
 'DEVELOPMENTAL_SCREENING_FOUR_EIGHT_PERSONAL',
 'DEVELOPMENTAL_SCREENING_EIGHT_TWELVE_COMMUNICATION',
 'DEVELOPMENTAL_SCREENING_EIGHT_TWELVE_GROSS_MOTOR',
 'DEVELOPMENTAL_SCREENING_EIGHT_TWELVE_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_EIGHT_TWELVE_PROBLEM',
 'DEVELOPMENTAL_SCREENING_EIGHT_TWELVE_PERSONAL',
 'DEVELOPMENTAL_SCREENING_TWELVE_SIXTEEN_COMMUNICATI',
 'DEVELOPMENTAL_SCREENING_TWELVE_SIXTEEN_GROSS_MOTOR',
 'DEVELOPMENTAL_SCREENING_TWELVE_SIXTEEN_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_TWELVE_SIXTEEN_PROBLEM',
 'DEVELOPMENTAL_SCREENING_TWELVE_SIXTEEN_PERSONAL',
 'DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_COMMUNICATI',
 'DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_GROSS_MOTOR',
 'CDR_RESPONSIBLE_PHYSICIAN_PHONE_EXT',
 'SCHOOL_READINESS_PLAYING',
 'SCHOOL_READINESS_DEVELOPMENT_CONCERNS',
 'SCHOOL_READINESS_BASIC_NEEDS_HELP',
 'CHECKLIST_EARLY_CHILDHOOD_REFERRAL_SPECIFY',
 'CHECKLIST_EARLY_CHILDHOOD_ENROLLMENT_SPECIFY',
 'CHECKLIST_RESOURCES_SPECIFY',
 'INTERIM_MEASURESIMPLEMENTED_OTHER',
 'INTERIM_MEASURES_IMPLEMENTED_FIRST_NAME',
 'INTERIM_MEASURES_IMPLEMENTED_LAST_NAME',
 'INTERIM_MEASURES_IMPLEMENTED_PHONE',
 'INTERIM_RELOCATION_ADDRESS_STREET',
 'INTERIM_RELOCATION_ADDRESS_CITY',
 'INTERIM_RELOCATION_ADDRESS_STATE',
 'INTERIM_RELOCATION_ADDRESS_ZIP',
 'INTERIM_RELOCATION_MEASURES_OTHER',
 'INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STREET',
 'INTERIM_ABATEMENT_RELOCATION_YES_CITY',
 'INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STATE',
 'INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_ZIP',
 'INTERIM_ABATEMENT_RELOCATION_YES_MEASURES_OTHER',
 'INTER_ABATEMENT_NO_RELOCATION_MEASURES_OTHER',
 'REFERRALS_INFORMATION_YES_SPECIFY',
 'REFERRALS_DSS_YES_ACTIONS',
 'REFERRAL_ABATEMENT_YES_SOURCE',
 'EDUCATIONAL_MATERIALS_RECEIVE_PACKET_NO_WHY_NOT',
 'EDUCATIONAL_MATERIALS_LANGUAGE_NO_ACTION',
 'EDUCATIONAL_MATERIALS_REVIEWED_NO_WHY_NOT_OTHER_SP',
 'EDUCATIONAL_MATERIALS_UNDERSTAND_NO_ACTION',
 'EPI_FOLLOWUP',
 'RN_FOLLOWUP',
 'CLIN_CHELATION_INPATIENT_SECTION',
 'CLIN_CHELATION_INPATIENT_STREET_ADDRESS',
 'CLIN_CHELATION_INPATIENT_CITY',
 'CLIN_CHELATION_INPATIENT_ZIP_CODE',
 'CLIN_CHELATION_INPATIENT_LEAD_SAFE_STEPS_OTHER_SPE',
 'CLIN_CHELATION_OUTPATIENT_SECTION',
 'CLIN_CHELATION_OUTPATIENT_STREET_ADDRESS',
 'CLIN_CHELATION_OUTPATIENT_CITY',
 'CLIN_CHELATION_OUTPATIENT_ZIP_CODE',
 'CLIN_CHELATION_OUTPATIENT_LEAD_SAFE_STEPS_OTHER_SP',
 'HI_lead_1',
 'HI_lead_2oth',
 'HI_lead_3',
 'HI_lead_4',
 'HI_lead_5',
 'HI_lead_7oth',
 'HI_lead_8',
 'HI_lead_26_oth',
 'Other Race Text',
 'DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_PROBLEM',
 'DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_PERSONAL',
 'DEVELOPMENTAL_SCREENING_TWENTY_TWENTYFOUR_COMMUNIC',
 'DEVELOPMENTAL_SCREENING_TWENTY_TWENTYFOUR_GROSS_MO',
 'DEVELOPMENTAL_SCREENING_TWENTY_TWENTYFOUR_FINE_MOT',
 'DEVELOPMENTAL_SCREENING_TWENTY_TWENTYFOUR_PROBLEM',
 'DEVELOPMENTAL_SCREENING_TWENTY_TWENTYFOUR_PERSONAL',
 'DEVELOPMENTAL_SCREENING_TWENTYFOUR_THIRTY_COMMUNIC',
 'DEVELOPMENTAL_SCREENING_TWENTYFOUR_THIRTY_GROSS_MO',
 'DEVELOPMENTAL_SCREENING_TWENTYFOUR_THIRTY_FINE_MOT',
 'DEVELOPMENTAL_SCREENING_TWENTYFOUR_THIRTY_PROBLEM',
 'DEVELOPMENTAL_SCREENING_TWENTYFOUR_THIRTY_PERSONAL',
 'DEVELOPMENTAL_SCREENING_THIRTY_THIRTYSIX_COMMUNICA',
 'DEVELOPMENTAL_SCREENING_THIRTY_THIRTYSIX_GROSS_MOT',
 'DEVELOPMENTAL_SCREENING_THIRTY_THIRTYSIX_FINE_MOTO',
 'DEVELOPMENTAL_SCREENING_THIRTY_THIRTYSIX_PROBLEM',
 'DEVELOPMENTAL_SCREENING_THIRTY_THIRTYSIX_PERSONAL',
 'DEVELOPMENTAL_SCREENING_THIRTYSIX_FORTYTWO_COMMUNI',
 'DEVELOPMENTAL_SCREENING_THIRTYSIX_FORTYTWO_GROSS_M',
 'DEVELOPMENTAL_SCREENING_THIRTYSIX_FORTYTWO_FINE_MO',
 'DEVELOPMENTAL_SCREENING_THIRTYSIX_FORTYTWO_PROBLEM',
 'DEVELOPMENTAL_SCREENING_THIRTYSIX_FORTYTWO_PERSONA',
 'DEVELOPMENTAL_SCREENING_FORTYTWO_FORTYEIGHT_COMMUN',
 'DEVELOPMENTAL_SCREENING_FORTYTWO_FORTYEIGHT_GROSS_',
 'DEVELOPMENTAL_SCREENING_FORTYTWO_FORTYEIGHT_FINE_M',
 'DEVELOPMENTAL_SCREENING_FORTYTWO_FORTYEIGHT_PROBLE',
 'DEVELOPMENTAL_SCREENING_FORTYTWO_FORTYEIGHT_PERSON',
 'DEVELOPMENTAL_SCREENING_FORTYEIGHT_FIFTYFOUR_COMMU',
 'DEVELOPMENTAL_SCREENING_FORTYEIGHT_FIFTYFOUR_GROSS',
 'DEVELOPMENTAL_SCREENING_FORTYEIGHT_FIFTYFOUR_FINE_',
 'DEVELOPMENTAL_SCREENING_FORTYEIGHT_FIFTYFOUR_PROBL',
 'DEVELOPMENTAL_SCREENING_FORTYEIGHT_FIFTYFOUR_PERSO',
 'DEVELOPMENTAL_SCREENING_FIFTYFOUR_SIXTY_COMMUNICAT',
 'DEVELOPMENTAL_SCREENING_FIFTYFOUR_SIXTY_GROSS_MOTO',
 'DEVELOPMENTAL_SCREENING_FIFTYFOUR_SIXTY_FINE_MOTOR',
 'DEVELOPMENTAL_SCREENING_FIFTYFOUR_SIXTY_PROBLEM',
 'DEVELOPMENTAL_SCREENING_FIFTYFOUR_SIXTY_PERSONAL',
 'CHECKLIST_TELEPHONE_FOLLOW_UP',
 'CHECKLIST_HIILEI_REFERRAL',
 'CHECKLIST_HIILEI_CONSENT',
 'CHECKLIST_DEVELOPMENTAL_SCREENING',
 'CHECKLIST_EIS_REFERRAL',
 'CHECKLIST_EIS_ENROLLMENT',
 'CHECKLIST_EARLY_CHILDHOOD_REFERRAL',
 'CHECKLIST_EARLY_CHILDHOOD_ENROLLMENT',
 'CHECKLIST_READING',
 'CHECKLIST_MEDIA',
 'CHECKLIST_MEDICAL_HOME',
 'CHECKLIST_VACCINATIONS',
 'CHECKLIST_INSURANCE',
 'CHECKLIST_INSURANCE_REFERRAL',
 'CHECKLIST_RESOURCES',
 'CHECKLIST_INVESTIGATION',
 'INTERIM_RELOCATION',
 'INTERIM_ABATEMENT_RELOCATION',
 'INTERIM_ABATEMENT_NO_RELOCATION',
 'REFERRALS_INFORMATION',
 'REFERRALS',
 'REFERRALS_WIC_REFERRAL',
 'REFERRALS_HEAD_START_REFERRAL',
 'NON_INSURED_UNDER_INSURED_QUEST_REFERRAL',
 'REFERRAL_BIRTH_TO_THREE_REFERRAL',
 'REFERRAL_ABATEMENT',
 'EDUCATIONAL_MATERIALS_RECEIVE_PACKET',
 'EDUCATIONAL_MATERIALS_LANGUAGE',
 'EDUCATIONAL_MATERIALS_REVIEWED',
 'EDUCATIONAL_MATERIALS_REVIEWED_NO_WHY_NOT',
 'EDUCATIONAL_MATERIALS_UNDERSTAND',
 'PEHSU_CONTACTED',
 'CLIN_CHELATION',
 'CLIN_CHELATION_INPATIENT_STATE',
 'CLIN_CHELATION_INPATIENT_COUNTY',
 'CLIN_CHELATION_INPATIENT_HAZARD',
 'CLIN_CHELATION_OUTPATIENT_STATE',
 'CLIN_CHELATION_OUTPATIENT_COUNTY',
 'CLIN_CHELATION_OUTPATIENT_HAZARD',
 'Non-occupational avocation or activity from which',
 'Was the exposure work-related.',
 'Hawaii Case Status',
 'HI_lead_2',
 'HI_lead_9',
 'HI_lead_12',
 'HI_lead_13',
 'HI_lead_14',
 'HI_lead_16',
 'HI_lead_18',
 'HI_lead_21',
 'HI_lead_22',
 'HI_lead_23',
 'HI_lead_25',
 'HI_lead_26',
 'Have they all been tested for lead?',
 'Spanish Origin',
 'Ethnic Group',
 'Have they all been tested for lead?',
 'PROBABLE_LEAD_SOURCE_DETERMINATION_TYPE',
 'PROBABLE_LEAD_CONFIDENCE_LEVEL',
 'PROBABLE_LEAD_SOURCE',
 'HG_LIGHT_DATE',
 'HG_THERMOMETER_DATE',
 'HG_THEROSTAT_DATE',
 'ONSET_DATE',
 'SS_JAUNDICE_DATE_BEGAN',
 'Blood Lead Level Date (MM/DD/YYYY)',
 'CHECKLIST_INVESTIGATION_DATE',
 'INTERIM_DATE',
 'INTERIM_RELOCATION_DATE',
 'INTERIM_ABATEMENT_RELOCATION_YES_DATE',
 'REFERRALS_INFORMATION_YES_DATE',
 'REFERRALS_DSS_YES_DATE',
 'REFERRAL_ABATEMENT_YES_DATE',
 'PEHSU_DATE',
 'CLIN_CHELATION_DATE',
 'CLIN_CHELATION_INPATIENT_DATE_DISCHARGE',
 'NEXT_BLOOD_TEST_DATE',
 'PROBABLE_LEAD_SOURCE_DATE',
 'AS_WATER_LOCATION_OTH',
 'AS_SEAFOOD_FREQ',
 'AS_SEAFOOD_AMT',
 'AS_SEAFOOD_TYPE',
 'AS_ADD_EXP',
 'CD_EXP_OTH',
 'HG_FISH_SPOT',
 'HG_FISH_TYPE_OTH',
 'HG_OTHER_DESC',
 'HG_WORK_SITE_OTH',
 'HG_EXP_OTH',
 'SYMPTOMS_MESSAGE',
 'SS_OTHER_SPECIFY',
 'CDR_RESPONSIBLE_PHYSICIAN_LAST_NAME',
 'CDR_RESPONSIBLE_PHYSICIAN_FIRST_NAME',
 'CDR_RESPONSIBLE_PHYSICIAN_ADDRESS1',
 'CDR_RESPONSIBLE_PHYSICIAN_ADDRESS2',
 'CDR_RESPONSIBLE_PHYSICIAN_CITY',
 'CDR_RESPONSIBLE_PHYSICIAN_ZIP',
 'CDR_RESPONSIBLE_PHYSICIAN_PHONE',
 'INTERIM_ABATEMENT_RELOCATION_YES_MEASURES',
 'INTERIM_ABATEMENT_NO_RELOCATION_MEASURES',
 'CLIN_CHELATION_TYPE',
 'CLIN_CHELATION_INPATIENT_LEAD_SAFE_STEPS',
 'CLIN_CHELATION_OUTPATIENT_LEAD_SAFE_STEPS',
 'SYMPTOMS',
 'INTERIM_MEASURES_IMPLEMENTED',
 'INTERIM_RELOCATION_MEASURES',
 'DEVELOPMENTAL_SCREENING',
 'HI_lead_7',
 'HI_lead_20a',
 'HI_lead_26',
 'Race Category',
 'Patient Detailed Race AIAN',
 'Patient Detailed Race Asian',
 'Patient Detailed Race Black or African American',
 'Patient Detailed Race NH or OPI',
 'Patient Detailed Race White',
 'HI_lead_18',
 'PROBABLE_LEAD_RECOMMENDATIONS',
 'PROBABLE_LEAD_RESOURCES',
 'HI_lead_6_no_children',
 'HI_lead_17',
 'HI_lead_19',
 'HI_lead_20',
 'HI_lead_24',
 'HI_lead_28',
 'HI_lead_8',
 'lead_investigation_notes',
 'HI_lead_13_details']

In [245]:
# Process the column values (eliminate the values in square brackets)
df_origami.loc[:,'Label'] = [ label.split(']')[1].strip() if ']' in label else label.strip() for label in df_origami.loc[:,'Label']]

In [246]:
# Clean up column names in both data sets
df_origami.loc[:,'Label'] =[ clean_up(q) for q in df_origami.loc[:,'Label']]

In [247]:
df_origami.loc[:,'Label'].value_counts()

Label
HI_lead_26                            2
HI_lead_8                             2
HI_lead_18                            2
Investigation Completed               2
Have they all been tested for lead    2
                                     ..
HG_FILLING_REPAIR                     1
HG_FILLING                            1
HG_WORK_SITE                          1
HG_COSMETIC                           1
HI_lead_13_details                    1
Name: count, Length: 394, dtype: int64

In [248]:
# duplicates labels exist but they are labels to different questions, so keep them
df_origami[df_origami.duplicated(['Label'],keep=False)]

                       Field                               Label
67               CustomText6                             Address
70               CustomText9                                Name
73              CustomText12                                Name
77              CustomText16                             Address
100             CustomDate14             Investigation Completed
102             CustomDate16             Investigation Completed
231             CustomText93                           HI_lead_8
320          CustomCode203ID                          HI_lead_18
325          CustomCode208ID                          HI_lead_26
326          CustomCode209ID  Have they all been tested for lead
329          CustomCode212ID  Have they all been tested for lead
382  CustomMultiSelectCode12                          HI_lead_26
389  CustomMultiSelectCode19                          HI_lead_18
398        CustomNarrative11                           HI_lead_8

In [249]:
# Do a semantic match between Maven Lead elements and Origami Lead labels

In [250]:
maven_elements = [str.replace(maven_de,'_',' ') for maven_de in df_maven_lead.Question]
origami_elements = [str.replace(col,'_',' ') for col in df_origami.Label]

In [251]:
origami_elements

['Case Lead ID',
 'Client',
 'Entry User',
 'Entry Date',
 'Modified User',
 'Modified Date',
 'IncidentID',
 'If pregnant was blood lead testing',
 'Is this a Child Case 16 yrs or Ad',
 'Specimen Source',
 'Test result at or above 35 gdL',
 'Reason for testing',
 'Performing lab type',
 'Test source of funding',
 'Medicaid',
 'Chelation therapy administered',
 'Chelated type',
 'Source of funding for the chelatio',
 'Developmental assessment cond',
 'We they tested for lead',
 'Abdominal Pain or Tenderness',
 'Bleeding gums',
 'Constipation',
 'Fatigue',
 'Headache',
 'Vomiting',
 'Hearing loss',
 'High blood pressure',
 'Loss of appetite',
 'Seizures',
 'Weight loss',
 'Other',
 'Do any teenages or adult',
 'Blood tested',
 'Are clothes cha',
 'Do they shower at work',
 'Do they wash hands',
 'Do they wash wo',
 'Does anyone in the home have a hobby i',
 'Does the child eat or chew on n',
 'Does the child eat dirt',
 'County',
 'Address type',
 'Type of Residence',
 'Ownership',
 'Current Address',
 'Residential ownership status',
 'Type of dwelling',
 'Dwelling with peeling chipping o',
 'Industrial hazard near dwelling',
 'Lead hazard',
 'Clearance performed',
 'Clearance testing results',
 'ISLAND',
 'HEAVY METALS',
 'WORK RELATED EXP',
 'AS EXP JOB ACTIVITY',
 'Additional Comments',
 'HI lead 6',
 'HI lead 10',
 'HI lead 11',
 'HI lead 15',
 'Accession Number',
 'Result measured in gdL',
 'Other reason',
 'Medicaid ID Number',
 'Name of Location',
 'Address',
 'Phone',
 'Average time spent at thi',
 'Name',
 'Relationship to subje',
 'Specify other symptoms',
 'Name',
 'Occupation',
 'Work place',
 'Length at occupat',
 'Address',
 'City',
 'Zip Code',
 'Other address type',
 'Please Specify',
 'Year Built',
 'Movedin Date',
 'Specify other',
 'COMP NAME',
 'AS WATER SOURCE OTH',
 'Report Date',
 'Specimen Collection Date',
 'Result Date',
 'Date completed',
 'Date of birth',
 'Movedout Date',
 'Date address referred for investiga',
 'Date first occupied',
 'Date last occupied',
 'Date Referred',
 'Date address investigation inspect',
 'Date remediation due',
 'Date clearance testing completed',
 'Investigation Completed',
 'Date address hazard remediation or',
 'Investigation Completed',
 'HG SWITCH DATE',
 'HG OTHER DATE',
 'HG BP GAUGE DATE',
 'HG BARO DATE',
 'Highest XRF reading in mgcm2 0000',
 'Highest window sill dust sample re',
 'Highest window well dust sample re',
 'Highest paint chip sample reading 00',
 'Highest soil sample reading in ppm 00',
 'Highest water sample reading in ppb',
 'HG FILLING RECENT NUM',
 'SS FEVER HIGHEST TEMP',
 'Blood Lead Level',
 'lead dust floor',
 'Case Type',
 'AS EXP OTH',
 'AS WATER SOURCE',
 'AS WATER LOCATION',
 'CD EXP JOB ACTIVITY',
 'CD MEAT SOURCE',
 'HG EXP FOOD SOURCE',
 'HG FISH LOC',
 'HG FISH TYPE',
 'HG FISH FREQ',
 'HG EXP JOB ACTIVITY',
 'HG EXP PRODUCT',
 'HG EXP EMISSIONS',
 'HG EXP BROKEN ITEM',
 'HG COSMETIC',
 'HG WORK SITE',
 'HG FILLING',
 'HG FILLING REPAIR',
 'HG FILLING RECENT',
 'HG FILLING REMOVE',
 'PATIENT SYMPTOMATIC',
 'SS FEVER',
 'SS FEVER HIGHEST TEMP SCALE',
 'SS HEADACHE',
 'SS MALAISE',
 'SS FATIGUE',
 'SS ABDOMINAL PAIN',
 'SS NAUSEA',
 'SS VOMITING',
 'SS ANOREXIA',
 'SS DARK URINE',
 'SS DIARRHEA',
 'SS JAUNDICE',
 'SS OTHER',
 'Date Type',
 'Did the patient die from this illness',
 'SCHOOL READINESS READING',
 'SCHOOL READINESS MEDIA',
 'SCHOOL READINESS DEVELOPMENT',
 'SCHOOL READINESS BASIC NEEDS',
 'DEVELOPMENTAL SCREENING ZERO TWO COMMUNICATION',
 'DEVELOPMENTAL SCREENING ZERO TWO GROSS MOTOR',
 'DEVELOPMENTAL SCREENING ZERO TWO FINE MOTOR',
 'DEVELOPMENTAL SCREENING ZERO TWO PROBLEM',
 'DEVELOPMENTAL SCREENING ZERO TWO PERSONAL',
 'DEVELOPMENTAL SCREENING TWO FOUR COMMUNICATION',
 'DEVELOPMENTAL SCREENING TWO FOUR GROSS MOTOR',
 'DEVELOPMENTAL SCREENING TWO FOUR FINE MOTOR',
 'DEVELOPMENTAL SCREENING TWO FOUR PROBLEM',
 'DEVELOPMENTAL SCREENING TWO FOUR PERSONAL',
 'DEVELOPMENTAL SCREENING FOUR EIGHT COMMUNICATION',
 'DEVELOPMENTAL SCREENING FOUR EIGHT GROSS MOTOR',
 'DEVELOPMENTAL SCREENING FOUR EIGHT FINE MOTOR',
 'DEVELOPMENTAL SCREENING FOUR EIGHT PROBLEM',
 'DEVELOPMENTAL SCREENING FOUR EIGHT PERSONAL',
 'DEVELOPMENTAL SCREENING EIGHT TWELVE COMMUNICATION',
 'DEVELOPMENTAL SCREENING EIGHT TWELVE GROSS MOTOR',
 'DEVELOPMENTAL SCREENING EIGHT TWELVE FINE MOTOR',
 'DEVELOPMENTAL SCREENING EIGHT TWELVE PROBLEM',
 'DEVELOPMENTAL SCREENING EIGHT TWELVE PERSONAL',
 'DEVELOPMENTAL SCREENING TWELVE SIXTEEN COMMUNICATI',
 'DEVELOPMENTAL SCREENING TWELVE SIXTEEN GROSS MOTOR',
 'DEVELOPMENTAL SCREENING TWELVE SIXTEEN FINE MOTOR',
 'DEVELOPMENTAL SCREENING TWELVE SIXTEEN PROBLEM',
 'DEVELOPMENTAL SCREENING TWELVE SIXTEEN PERSONAL',
 'DEVELOPMENTAL SCREENING SIXTEEN TWENTY COMMUNICATI',
 'DEVELOPMENTAL SCREENING SIXTEEN TWENTY GROSS MOTOR',
 'CDR RESPONSIBLE PHYSICIAN PHONE EXT',
 'SCHOOL READINESS PLAYING',
 'SCHOOL READINESS DEVELOPMENT CONCERNS',
 'SCHOOL READINESS BASIC NEEDS HELP',
 'CHECKLIST EARLY CHILDHOOD REFERRAL SPECIFY',
 'CHECKLIST EARLY CHILDHOOD ENROLLMENT SPECIFY',
 'CHECKLIST RESOURCES SPECIFY',
 'INTERIM MEASURESIMPLEMENTED OTHER',
 'INTERIM MEASURES IMPLEMENTED FIRST NAME',
 'INTERIM MEASURES IMPLEMENTED LAST NAME',
 'INTERIM MEASURES IMPLEMENTED PHONE',
 'INTERIM RELOCATION ADDRESS STREET',
 'INTERIM RELOCATION ADDRESS CITY',
 'INTERIM RELOCATION ADDRESS STATE',
 'INTERIM RELOCATION ADDRESS ZIP',
 'INTERIM RELOCATION MEASURES OTHER',
 'INTERIM ABATEMENT RELOCATION YES ADDRESS STREET',
 'INTERIM ABATEMENT RELOCATION YES CITY',
 'INTERIM ABATEMENT RELOCATION YES ADDRESS STATE',
 'INTERIM ABATEMENT RELOCATION YES ADDRESS ZIP',
 'INTERIM ABATEMENT RELOCATION YES MEASURES OTHER',
 'INTER ABATEMENT NO RELOCATION MEASURES OTHER',
 'REFERRALS INFORMATION YES SPECIFY',
 'REFERRALS DSS YES ACTIONS',
 'REFERRAL ABATEMENT YES SOURCE',
 'EDUCATIONAL MATERIALS RECEIVE PACKET NO WHY NOT',
 'EDUCATIONAL MATERIALS LANGUAGE NO ACTION',
 'EDUCATIONAL MATERIALS REVIEWED NO WHY NOT OTHER SP',
 'EDUCATIONAL MATERIALS UNDERSTAND NO ACTION',
 'EPI FOLLOWUP',
 'RN FOLLOWUP',
 'CLIN CHELATION INPATIENT SECTION',
 'CLIN CHELATION INPATIENT STREET ADDRESS',
 'CLIN CHELATION INPATIENT CITY',
 'CLIN CHELATION INPATIENT ZIP CODE',
 'CLIN CHELATION INPATIENT LEAD SAFE STEPS OTHER SPE',
 'CLIN CHELATION OUTPATIENT SECTION',
 'CLIN CHELATION OUTPATIENT STREET ADDRESS',
 'CLIN CHELATION OUTPATIENT CITY',
 'CLIN CHELATION OUTPATIENT ZIP CODE',
 'CLIN CHELATION OUTPATIENT LEAD SAFE STEPS OTHER SP',
 'HI lead 1',
 'HI lead 2oth',
 'HI lead 3',
 'HI lead 4',
 'HI lead 5',
 'HI lead 7oth',
 'HI lead 8',
 'HI lead 26 oth',
 'Other Race Text',
 'DEVELOPMENTAL SCREENING SIXTEEN TWENTY FINE MOTOR',
 'DEVELOPMENTAL SCREENING SIXTEEN TWENTY PROBLEM',
 'DEVELOPMENTAL SCREENING SIXTEEN TWENTY PERSONAL',
 'DEVELOPMENTAL SCREENING TWENTY TWENTYFOUR COMMUNIC',
 'DEVELOPMENTAL SCREENING TWENTY TWENTYFOUR GROSS MO',
 'DEVELOPMENTAL SCREENING TWENTY TWENTYFOUR FINE MOT',
 'DEVELOPMENTAL SCREENING TWENTY TWENTYFOUR PROBLEM',
 'DEVELOPMENTAL SCREENING TWENTY TWENTYFOUR PERSONAL',
 'DEVELOPMENTAL SCREENING TWENTYFOUR THIRTY COMMUNIC',
 'DEVELOPMENTAL SCREENING TWENTYFOUR THIRTY GROSS MO',
 'DEVELOPMENTAL SCREENING TWENTYFOUR THIRTY FINE MOT',
 'DEVELOPMENTAL SCREENING TWENTYFOUR THIRTY PROBLEM',
 'DEVELOPMENTAL SCREENING TWENTYFOUR THIRTY PERSONAL',
 'DEVELOPMENTAL SCREENING THIRTY THIRTYSIX COMMUNICA',
 'DEVELOPMENTAL SCREENING THIRTY THIRTYSIX GROSS MOT',
 'DEVELOPMENTAL SCREENING THIRTY THIRTYSIX FINE MOTO',
 'DEVELOPMENTAL SCREENING THIRTY THIRTYSIX PROBLEM',
 'DEVELOPMENTAL SCREENING THIRTY THIRTYSIX PERSONAL',
 'DEVELOPMENTAL SCREENING THIRTYSIX FORTYTWO COMMUNI',
 'DEVELOPMENTAL SCREENING THIRTYSIX FORTYTWO GROSS M',
 'DEVELOPMENTAL SCREENING THIRTYSIX FORTYTWO FINE MO',
 'DEVELOPMENTAL SCREENING THIRTYSIX FORTYTWO PROBLEM',
 'DEVELOPMENTAL SCREENING THIRTYSIX FORTYTWO PERSONA',
 'DEVELOPMENTAL SCREENING FORTYTWO FORTYEIGHT COMMUN',
 'DEVELOPMENTAL SCREENING FORTYTWO FORTYEIGHT GROSS ',
 'DEVELOPMENTAL SCREENING FORTYTWO FORTYEIGHT FINE M',
 'DEVELOPMENTAL SCREENING FORTYTWO FORTYEIGHT PROBLE',
 'DEVELOPMENTAL SCREENING FORTYTWO FORTYEIGHT PERSON',
 'DEVELOPMENTAL SCREENING FORTYEIGHT FIFTYFOUR COMMU',
 'DEVELOPMENTAL SCREENING FORTYEIGHT FIFTYFOUR GROSS',
 'DEVELOPMENTAL SCREENING FORTYEIGHT FIFTYFOUR FINE ',
 'DEVELOPMENTAL SCREENING FORTYEIGHT FIFTYFOUR PROBL',
 'DEVELOPMENTAL SCREENING FORTYEIGHT FIFTYFOUR PERSO',
 'DEVELOPMENTAL SCREENING FIFTYFOUR SIXTY COMMUNICAT',
 'DEVELOPMENTAL SCREENING FIFTYFOUR SIXTY GROSS MOTO',
 'DEVELOPMENTAL SCREENING FIFTYFOUR SIXTY FINE MOTOR',
 'DEVELOPMENTAL SCREENING FIFTYFOUR SIXTY PROBLEM',
 'DEVELOPMENTAL SCREENING FIFTYFOUR SIXTY PERSONAL',
 'CHECKLIST TELEPHONE FOLLOW UP',
 'CHECKLIST HIILEI REFERRAL',
 'CHECKLIST HIILEI CONSENT',
 'CHECKLIST DEVELOPMENTAL SCREENING',
 'CHECKLIST EIS REFERRAL',
 'CHECKLIST EIS ENROLLMENT',
 'CHECKLIST EARLY CHILDHOOD REFERRAL',
 'CHECKLIST EARLY CHILDHOOD ENROLLMENT',
 'CHECKLIST READING',
 'CHECKLIST MEDIA',
 'CHECKLIST MEDICAL HOME',
 'CHECKLIST VACCINATIONS',
 'CHECKLIST INSURANCE',
 'CHECKLIST INSURANCE REFERRAL',
 'CHECKLIST RESOURCES',
 'CHECKLIST INVESTIGATION',
 'INTERIM RELOCATION',
 'INTERIM ABATEMENT RELOCATION',
 'INTERIM ABATEMENT NO RELOCATION',
 'REFERRALS INFORMATION',
 'REFERRALS',
 'REFERRALS WIC REFERRAL',
 'REFERRALS HEAD START REFERRAL',
 'NON INSURED UNDER INSURED QUEST REFERRAL',
 'REFERRAL BIRTH TO THREE REFERRAL',
 'REFERRAL ABATEMENT',
 'EDUCATIONAL MATERIALS RECEIVE PACKET',
 'EDUCATIONAL MATERIALS LANGUAGE',
 'EDUCATIONAL MATERIALS REVIEWED',
 'EDUCATIONAL MATERIALS REVIEWED NO WHY NOT',
 'EDUCATIONAL MATERIALS UNDERSTAND',
 'PEHSU CONTACTED',
 'CLIN CHELATION',
 'CLIN CHELATION INPATIENT STATE',
 'CLIN CHELATION INPATIENT COUNTY',
 'CLIN CHELATION INPATIENT HAZARD',
 'CLIN CHELATION OUTPATIENT STATE',
 'CLIN CHELATION OUTPATIENT COUNTY',
 'CLIN CHELATION OUTPATIENT HAZARD',
 'Nonoccupational avocation or activity from which',
 'Was the exposure workrelated',
 'Hawaii Case Status',
 'HI lead 2',
 'HI lead 9',
 'HI lead 12',
 'HI lead 13',
 'HI lead 14',
 'HI lead 16',
 'HI lead 18',
 'HI lead 21',
 'HI lead 22',
 'HI lead 23',
 'HI lead 25',
 'HI lead 26',
 'Have they all been tested for lead',
 'Spanish Origin',
 'Ethnic Group',
 'Have they all been tested for lead',
 'PROBABLE LEAD SOURCE DETERMINATION TYPE',
 'PROBABLE LEAD CONFIDENCE LEVEL',
 'PROBABLE LEAD SOURCE',
 'HG LIGHT DATE',
 'HG THERMOMETER DATE',
 'HG THEROSTAT DATE',
 'ONSET DATE',
 'SS JAUNDICE DATE BEGAN',
 'Blood Lead Level Date MMDDYYYY',
 'CHECKLIST INVESTIGATION DATE',
 'INTERIM DATE',
 'INTERIM RELOCATION DATE',
 'INTERIM ABATEMENT RELOCATION YES DATE',
 'REFERRALS INFORMATION YES DATE',
 'REFERRALS DSS YES DATE',
 'REFERRAL ABATEMENT YES DATE',
 'PEHSU DATE',
 'CLIN CHELATION DATE',
 'CLIN CHELATION INPATIENT DATE DISCHARGE',
 'NEXT BLOOD TEST DATE',
 'PROBABLE LEAD SOURCE DATE',
 'AS WATER LOCATION OTH',
 'AS SEAFOOD FREQ',
 'AS SEAFOOD AMT',
 'AS SEAFOOD TYPE',
 'AS ADD EXP',
 'CD EXP OTH',
 'HG FISH SPOT',
 'HG FISH TYPE OTH',
 'HG OTHER DESC',
 'HG WORK SITE OTH',
 'HG EXP OTH',
 'SYMPTOMS MESSAGE',
 'SS OTHER SPECIFY',
 'CDR RESPONSIBLE PHYSICIAN LAST NAME',
 'CDR RESPONSIBLE PHYSICIAN FIRST NAME',
 'CDR RESPONSIBLE PHYSICIAN ADDRESS1',
 'CDR RESPONSIBLE PHYSICIAN ADDRESS2',
 'CDR RESPONSIBLE PHYSICIAN CITY',
 'CDR RESPONSIBLE PHYSICIAN ZIP',
 'CDR RESPONSIBLE PHYSICIAN PHONE',
 'INTERIM ABATEMENT RELOCATION YES MEASURES',
 'INTERIM ABATEMENT NO RELOCATION MEASURES',
 'CLIN CHELATION TYPE',
 'CLIN CHELATION INPATIENT LEAD SAFE STEPS',
 'CLIN CHELATION OUTPATIENT LEAD SAFE STEPS',
 'SYMPTOMS',
 'INTERIM MEASURES IMPLEMENTED',
 'INTERIM RELOCATION MEASURES',
 'DEVELOPMENTAL SCREENING',
 'HI lead 7',
 'HI lead 20a',
 'HI lead 26',
 'Race Category',
 'Patient Detailed Race AIAN',
 'Patient Detailed Race Asian',
 'Patient Detailed Race Black or African American',
 'Patient Detailed Race NH or OPI',
 'Patient Detailed Race White',
 'HI lead 18',
 'PROBABLE LEAD RECOMMENDATIONS',
 'PROBABLE LEAD RESOURCES',
 'HI lead 6 no children',
 'HI lead 17',
 'HI lead 19',
 'HI lead 20',
 'HI lead 24',
 'HI lead 28',
 'HI lead 8',
 'lead investigation notes',
 'HI lead 13 details']

In [252]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [253]:
# Compute embeddings
embeddings_maven = model.encode(maven_elements)
embeddings_origami = model.encode(origami_elements)

In [254]:
print(len(embeddings_origami))
print(len(embeddings_maven))
embeddings_origami
embeddings_maven

401
606

array([[-0.0020506 , -0.04598626, -0.04524118, ...,  0.01019603,
         0.0600717 , -0.01581826],
       [-0.080986  ,  0.06571371, -0.00726671, ..., -0.03971622,
         0.06275451, -0.00660688],
       [-0.01527976,  0.01455189, -0.0803012 , ...,  0.00756959,
         0.01350452, -0.00275409],
       ...,
       [-0.01195142,  0.04254857,  0.08214842, ..., -0.01518289,
        -0.02453376,  0.0252025 ],
       [-0.06644832,  0.03604519,  0.10580117, ..., -0.01695742,
         0.02714118,  0.0212451 ],
       [-0.0375696 ,  0.05908274,  0.00948133, ...,  0.02978237,
        -0.01489797, -0.0133038 ]], dtype=float32)

In [255]:
# Compute cosine similarities
similarities = model.similarity(embeddings_maven,embeddings_origami)

In [256]:
similarities

tensor([[ 0.0258,  0.1144, -0.0019,  ...,  0.2399,  0.0640,  0.2023],
        [ 0.1138,  0.1608, -0.0025,  ...,  0.0504,  0.1517,  0.0842],
        [ 0.0338, -0.0344, -0.0397,  ...,  0.1266,  0.0640,  0.1591],
        ...,
        [ 0.1462,  0.2037,  0.1194,  ...,  0.1201,  0.1136,  0.1390],
        [ 0.1729,  0.1440,  0.1463,  ...,  0.0985,  0.1070,  0.1319],
        [ 0.1609,  0.0577,  0.0730,  ...,  0.0437,  0.0396,  0.0893]])

In [257]:
type(similarities)
len(similarities)

606

In [258]:
df_similarities = pd.DataFrame(similarities,index=df_maven_lead.Question,columns=original_labels)

In [259]:
df_similarities

,Case Lead ID,Client,Entry User,Entry Date,Modified User,Modified Date,IncidentID,"[lead_preg_blt]If pregnant, was blood lead testing",[lead_under16]Is this a Child Case (<16 yrs) or Ad,[lead_bl_specsource]Specimen Source,...,PROBABLE_LEAD_RESOURCES,HI_lead_6_no_children,HI_lead_17,HI_lead_19,HI_lead_20,HI_lead_24,HI_lead_28,HI_lead_8,lead_investigation_notes,HI_lead_13_details
Question,,,,,,,,,,,,,,,,,,,,,
ANY_OVER_5_OUTPUT,0.025803,0.114357,-0.001872,-0.041852,0.006444,-0.036348,0.040639,0.053973,-0.016145,0.078986,...,0.138921,0.259962,0.226058,0.198540,0.272845,0.235286,0.235718,0.239852,0.063962,0.202338
VENOUS_CONFIRMED_DISPLAY,0.113808,0.160789,-0.002502,0.032497,0.035942,0.068626,0.045402,0.300372,0.136487,0.192706,...,0.078033,0.069234,0.056359,0.076221,0.065648,0.078259,0.051564,0.050370,0.151701,0.084232
MAX_VENOUS_BLL_RANGE_OUTPUT,0.033788,-0.034410,-0.039742,-0.000766,-0.029528,-0.007219,-0.030989,0.224953,-0.015748,0.132655,...,0.096739,0.114929,0.130708,0.136197,0.146979,0.124870,0.118783,0.126571,0.064016,0.159142
MAX_VENOUS_BLL_OUTPUT,0.056942,-0.009140,-0.033509,-0.007262,-0.018913,0.007159,0.008254,0.205379,0.001018,0.135731,...,0.058997,0.097167,0.117021,0.112082,0.125881,0.101424,0.099759,0.104436,0.050632,0.141410
MAX_VENOUS_BLL_DATE_OUTPUT,0.059105,-0.038171,-0.045077,0.384399,0.001480,0.368358,0.009315,0.221654,0.101369,0.172937,...,0.030890,0.054688,0.118256,0.121773,0.101268,0.108117,0.116337,0.081822,0.065683,0.120927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DR_OVERDUE_TEST_DATE,0.192236,-0.008107,-0.106171,0.315164,0.037759,0.367981,0.086776,0.333878,0.183493,0.156000,...,0.111712,0.131025,0.160527,0.178756,0.150856,0.164453,0.151854,0.121792,0.207612,0.146040
DR_MAILING_ADDRESS,0.216611,0.207069,0.260992,0.113655,0.286297,0.131592,0.246804,0.050145,0.172110,0.107888,...,0.048195,0.091866,0.151359,0.176754,0.160173,0.149623,0.175883,0.165202,0.106563,0.174280
DR_MAILING_CITY,0.146156,0.203670,0.119402,0.099299,0.180808,0.123937,0.229790,0.091015,0.204169,0.125451,...,0.073077,0.120737,0.150558,0.145556,0.121450,0.110293,0.137216,0.120115,0.113576,0.139016
DR_MAILING_STATE,0.172902,0.143973,0.146268,0.130968,0.177673,0.113402,0.180169,0.090338,0.248882,0.055802,...,0.041414,0.072867,0.100402,0.116263,0.093968,0.091355,0.096847,0.098535,0.107039,0.131873
DR_MAILING_ZIPCODE,0.160910,0.057748,0.072989,0.127668,0.133888,0.134524,0.122705,0.098742,0.102447,0.038297,...,0.020210,0.001292,0.072242,0.057860,0.053499,0.075093,0.053003,0.043748,0.039563,0.089323

In [260]:
df_similarities.to_csv('output/similarity_scores_lead.csv')

In [267]:
df_similarities.loc['DEVELOPMENTAL_SCREENING',:]

Case Lead ID                0.073111
Client                      0.064448
Entry User                  0.051299
Entry Date                  0.064655
Modified User               0.008360
                              ...
HI_lead_24                  0.084902
HI_lead_28                  0.078631
HI_lead_8                   0.087034
lead_investigation_notes    0.129956
HI_lead_13_details          0.068488
Name: DEVELOPMENTAL_SCREENING, Length: 401, dtype: float32

In [268]:
df_maven_lead = df_maven_lead.reset_index(drop=True)
df_maven_lead.columns

Index(['Model', 'question_number', 'depth', 'Question', 'Question.Package.ID',
       'Question.Package.Name', 'Message', 'mmg_element', 'cste_element'],
      dtype='object')

In [269]:
df_output = df_maven_lead[['Model','depth','Question','Message','mmg_element','cste_element']]

In [ ]:
#For every maven element (index), identify origami elements (column) that is the best match

filtered=[]
for idx in df_similarities.index:
    # Looking for columns with score higher than 0.92
    v = df_similarities.loc[idx,:]>0.92

    # Get the column with the maximum score
    max=0.0
    max_col=''
    for i,col in enumerate(df_similarities.columns):
        if v.iloc[i]==True:
            if df_similarities.loc[idx,col] > max:
                max = df_similarities.loc[idx,col]
                max_col=col

    #filtered.append({col:df_similarities.loc[idx,col]})
    print(idx+','+max_col+':'+str(max)+'\n')
    filtered.append({'Question':idx,'target_label':max_col})

ANY_OVER_5_OUTPUT,:0.0

VENOUS_CONFIRMED_DISPLAY,:0.0

MAX_VENOUS_BLL_RANGE_OUTPUT,:0.0

MAX_VENOUS_BLL_OUTPUT,:0.0

MAX_VENOUS_BLL_DATE_OUTPUT,:0.0

BLL_DECLINE_OUTPUT,:0.0

BLL_TOTAL_DECLINING_OUTPUT,:0.0

LATE_FOLLOW_UP_OVER_RIDE,:0.0

TESTING_DUE_DATE_OUTPUT,:0.0

LATEST_VENOUS_BLL_OUTPUT,:0.0

LATEST_VENOUS_BLL_DATE_OUTPUT,:0.0

LATEST_VENOUS_BLL_UNDER_5_OUTPUT,:0.0

LATEST_VENOUS_BLL_UNDER_5_DATE_OUTPUT,:0.0

LATEST_BLL_OUTPUT,:0.0

LATEST_BLL_DATE_OUTPUT,:0.0

LATEST_BLL_TYPE_OUTPUT,:0.0

LATEST_VENOUS_BLL_UNDER_5_TRUE_FALSE_DISPLAY,:0.0

CASE_CLOSURE_REASON,:0.0

CASE_CLOSURE_DATE,:0.0

REPORTED_BLOOD_LEVEL,:0.0

EPI_REQUIRED,:0.0

PHN_SECTION_LOOKUP,:0.0

PHN_ASSIGNED,:0.0

CONTACT_POINT_POSTAL_CODE_CHECK_DISPLAY,:0.0

PRIMARY_HOME_ZIP_CHECK,:0.0

REPORTING_SOURCE,:0.0

CDC_REPORTED_DATE,:0.0

CDC_REPORTED_DATE_OPERATION,:0.0

LEAD_BROCHURE_DATE,:0.0

DATE_OF_CONTACT,:0.0

DATE_OF_CONTACT_DATE_TYPE,:0.0

DATE_OF_CONTACT_DATE_TYPE_OTHER_SPECIFY,:0.0

DATE_OF_CONTACT_PERSON_CONTACTED,:0.0

DATE_OF_CONTACT_DATE_METHOD,:0.0

DATE_OF_CONTACT_DATE_METHOD_OTHER_SPECIFY,:0.0

DATE_OF_CONTACT_REASON,:0.0

EARLY_FOLLOW_UP_DATE,:0.0

LATE_FOLLOW_UP_DATE,:0.0

DOH_FILL_MSG,:0.0

PHN_FILL_MSG,:0.0

FORCE_PROPERTY_INVESTIGATION,:0.0

EBLL_CASE_OPEN_DATE,:0.0

EBLL_CASE_CLOSE_DATE,:0.0

RELEVANT_ADDRESS_DATE,:0.0

PRIMARY_RELEVANT_ADDRESS,:0.0

LAB_FACILITY_STATS,:0.0

PRODUCT,:0.0

EVENT_DATE,:0.0

ENABLE_EPI_FORM_HIDDEN,:0.0

HIGHEST_BLOOD_LEAD_LEVEL,:0.0

LATEST_CAPILLARY_LEAD_LEVEL,:0.0

LATEST_CAPILLARY_LEAD_LEVEL_DATE,:0.0

BLOOD_LEAD_LEVEL,Blood Lead Level:1.0

BLOOD_LEAD_LEVEL_DATE,:0.0

BLOOD_LEAD_LEVEL_CURRENT,:0.0

BLOOD_LEAD_LEVEL_CURRENT_DATE,:0.0

LAB_VALIDATION_DATES,:0.0

LAB_VALIDATION_NUMERIC_RESULT,:0.0

VALIDATION_INCOMPLETE_PRIMARY_ADDRESS,:0.0

EDUCATIONAL_MATERIALS_RECEIVE_PACKET,EDUCATIONAL_MATERIALS_RECEIVE_PACKET:1.0

EDUCATIONAL_MATERIALS_RECEIVE_PACKET_NO_WHY_NOT,EDUCATIONAL_MATERIALS_RECEIVE_PACKET_NO_WHY_NOT:1.0000001

EDUCATIONAL_MATERIALS_LANGUAGE,EDUCATIONAL_MATERIALS_LANGUAGE:0.9999999

EDUCATIONAL_MATERIALS_LANGUAGE_NO_ACTION,EDUCATIONAL_MATERIALS_LANGUAGE_NO_ACTION:0.99999976

EDUCATIONAL_MATERIALS_REVIEWED,EDUCATIONAL_MATERIALS_REVIEWED:0.99999994

EDUCATIONAL_MATERIALS_REVIEWED_NO_WHY_NOT,EDUCATIONAL_MATERIALS_REVIEWED_NO_WHY_NOT:1.0000002

EDUCATIONAL_MATERIALS_REVIEWED_NO_WHY_NOT_OTHER_SPECIFY,:0.0

EDUCATIONAL_MATERIALS_UNDERSTAND,EDUCATIONAL_MATERIALS_UNDERSTAND:1.0000002

EDUCATIONAL_MATERIALS_UNDERSTAND_NO_ACTION,EDUCATIONAL_MATERIALS_UNDERSTAND_NO_ACTION:1.0000001

EPI_FOLLOWUP,EPI_FOLLOWUP:1.0

RN_FOLLOWUP,RN_FOLLOWUP:1.0000001

CHILD_DOB,:0.0

AGE,:0.0

CHILD_SAVE_INFO,:0.0

CHILD_PARTY_ID_OTHER_CHILD,:0.0

CHILD_LINK_TYPE,:0.0

CHILD_STATUS,:0.0

WIC_MOM_PREGNANCY,:0.0

CHILD_BIRTH_SEQUENCE,:0.0

CHILD_PLURALITY,:0.0

CHILD_VITALS_ID,:0.0

CHILD_IMMUNIZATION_NUMBER,:0.0

CHILD_MEDICAID_NUMBER,:0.0

CHILD_ENROLLED_CWF,:0.0

CHILD_ENROLLED_QUEST_INTEGRATION,:0.0

CHILD_ENROLLED_SPED,:0.0

CHILD_HISPANIC,:0.0

CHILD_RACE,:0.0

CHILD_RACE_AMERICAN_INDIAN_ALASKAN_NATIVE_DETAIL,:0.0

CHILD_RACE_ASIAN_DETAIL,:0.0

CHILD_RACE_BLACK_AFRICAN_AMERICAN_DETAIL,:0.0

CHILD_RACE_NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DETAIL,:0.0

CHILD_RACE_WHITE_DETAIL,:0.0

RACE_OTHER_SPECIFY,:0.0

CHILD_RACE_FROM_SIGNAL,:0.0

PRIMARY_LANGUAGE,:0.0

PRIMARY_LANGUAGE_OTHER_SPECIFY,:0.0

CDC_CLIENT_ID,:0.0

PA_CDC_CHILD_ID,:0.0

CDC_ADDR_ID,:0.0

CHILD_GENDER_BIRTH,:0.0

CHILD_GENDER,:0.0

CHILD_LAST_NAME,:0.0

CHILD_MIDDLE_NAME,:0.0

CHILD_FIRST_NAME,:0.0

CHILD_EVENT_ID_OTHER_CHILD,:0.0

GUARDIAN_FIRST_NAME,:0.0

GUARDIAN_MIDDLE_NAME,:0.0

GUARDIAN_LAST_NAME,:0.0

GUARDIAN_STREET_ADDRESS,:0.0

GUARDIAN_CITY,:0.0

GUARDIAN_STATE,:0.0

CURRENT_ISLAND,:0.0

GUARDIAN_ZIP_CODE,:0.0

GUARDIAN_COUNTY,:0.0

GUARDIAN_TELEPHONE_HOME,:0.0

GUARDIAN_TELEPHONE_WORK,:0.0

GUARDIAN_TELEPHONE_CELL,:0.0

OTHER_CHILD_ADD_NEW,:0.0

OTHER_CHILD_EVENT_ID,:0.0

OTHER_CHILD_CREATE_EVENT,:0.0

OTHER_CHILD_PARTY,:0.0

OTHER_CHILD_EVENT_CREATED,:0.0

OTHER_CHILD_PARTY_CREATED,:0.0

OTHER_CHILD_LINK_CREATED,:0.0

OTHER_CHILD_LINK_TYPE,:0.0

OTHER_CHILD_DOB,:0.0

OTHER_CHILD_FIRST_NAME,:0.0

OTHER_CHILD_LAST_NAME,:0.0

OTHER_CHILD_GENDER,:0.0

OTHER_CHILD_SAVE_INFO,:0.0

PATIENT_HCP,:0.0

PATIENT_HCP_STREET1,:0.0

PATIENT_HCP_STREET2,:0.0

PATIENT_HCP_CITY,:0.0

PATIENT_HCP_STATE,:0.0

PATIENT_HCP_ZIP,:0.0

PATIENT_HCP_PHONE,:0.0

INSURANCE_TYPE,:0.0

INSURANCE_TYPE_OTHER_DESC,:0.0

LAB_FACILITY_QUESTION,:0.0

PEHSU_CONTACTED,PEHSU_CONTACTED:0.99999994

PEHSU_DATE,PEHSU_DATE:1.0

CLIN_CHELATION,CLIN_CHELATION:1.0000002

CLIN_CHELATION_DATE,CLIN_CHELATION_DATE:1.0

CLIN_CHELATION_TYPE,CLIN_CHELATION_TYPE:0.9999999

CLIN_CHELATION_INPATIENT_SECTION,CLIN_CHELATION_INPATIENT_SECTION:0.9999999

CLIN_CHELATION_INPATIENT_DATE_DISCHARGE,CLIN_CHELATION_INPATIENT_DATE_DISCHARGE:1.0

CLIN_CHELATION_INPATIENT_ADDRESS,CLIN_CHELATION_INPATIENT_STREET_ADDRESS:0.9392642

CLIN_CHELATION_INPATIENT_STREET_ADDRESS,CLIN_CHELATION_INPATIENT_STREET_ADDRESS:1.0

CLIN_CHELATION_INPATIENT_CITY,CLIN_CHELATION_INPATIENT_CITY:0.9999999

CLIN_CHELATION_INPATIENT_STATE,CLIN_CHELATION_INPATIENT_STATE:1.0

CLIN_CHELATION_INPATIENT_ZIP_CODE,CLIN_CHELATION_INPATIENT_ZIP_CODE:0.99999994

CLIN_CHELATION_INPATIENT_COUNTY,CLIN_CHELATION_INPATIENT_COUNTY:0.99999994

CLIN_CHELATION_INPATIENT_LEAD_SAFE_STEPS,CLIN_CHELATION_INPATIENT_LEAD_SAFE_STEPS:1.0000002

CLIN_CHELATION_INPATIENT_LEAD_SAFE_STEPS_OTHER_SPECIFY,CLIN_CHELATION_INPATIENT_LEAD_SAFE_STEPS:0.9916897

CLIN_CHELATION_INPATIENT_HAZARD,CLIN_CHELATION_INPATIENT_HAZARD:1.0

CLIN_CHELATION_OUTPATIENT_SECTION,CLIN_CHELATION_OUTPATIENT_SECTION:1.0

CLIN_CHELATION_OUTPATIENT_RESIDING,CLIN_CHELATION_OUTPATIENT_STATE:0.9639839

CLIN_CHELATION_OUTPATIENT_STREET_ADDRESS,CLIN_CHELATION_OUTPATIENT_STREET_ADDRESS:1.0

CLIN_CHELATION_OUTPATIENT_CITY,CLIN_CHELATION_OUTPATIENT_CITY:1.0000002

CLIN_CHELATION_OUTPATIENT_STATE,CLIN_CHELATION_OUTPATIENT_STATE:1.0

CLIN_CHELATION_OUTPATIENT_ZIP_CODE,CLIN_CHELATION_OUTPATIENT_ZIP_CODE:1.0000002

CLIN_CHELATION_OUTPATIENT_COUNTY,CLIN_CHELATION_OUTPATIENT_COUNTY:1.0000002

CLIN_CHELATION_OUTPATIENT_LEAD_SAFE_STEPS,CLIN_CHELATION_OUTPATIENT_LEAD_SAFE_STEPS:1.0

CLIN_CHELATION_OUTPATIENT_LEAD_SAFE_STEPS_OTHER_SPECIFY,CLIN_CHELATION_OUTPATIENT_LEAD_SAFE_STEPS:0.98945415

CLIN_CHELATION_OUTPATIENT_HAZARD,CLIN_CHELATION_OUTPATIENT_HAZARD:1.0

NEXT_BLOOD_TEST_DATE,NEXT_BLOOD_TEST_DATE:0.99999994

SYMPTOMS,SYMPTOMS:1.0000001

SYMPTOMS_OTHER_DESC,:0.0

RESIDENTIAL_YEAR_BUILT,:0.0

PROPERTY_OWN_RENT,:0.0

PROPERTY_SUBSIDY,:0.0

PROPERTY_SUBSIDY_YES_WHAT_TYPE,:0.0

PROPERTY_SUBSIDY_YES_WHAT_TYPE_OTHER_SPECIFY,:0.0

RESIDENCE_HISTORY_WHERE,:0.0

RESIDENCY_HISTORY_WHEN,:0.0

RESIDENCY_HISTORY_COMPLETE,:0.0

RESIDENCY_HISTORY_DATE,:0.0

RESIDENCY_HISTORY_DATE_END_DATE,:0.0

RESIDENCE_HISTORY_DATE_STREET_ADDRESS,:0.0

RESIDENCE_HISTORY_DATE_CITY,:0.0

RESIDENCE_HISTORY_DATE_STATE,:0.0

RESIDENCE_HISTORY_DATE_ZIP_CODE,:0.0

RESIDENCE_HISTORY_DATE_COUNTY,:0.0

RESIDENCY_HISTORY_DATE_AGE,:0.0

RESIDENCY_HISTORY_DATE_CONDITION,:0.0

RESIDENCY_HISTORY_DATE_CONDITION_OTHER_SECIFY,:0.0

RESIDENCE_HISTORY_DATE_PAINT,:0.0

RESIDENCE_HISTORY_DATE_REMODELLING,:0.0

RESIDENCY_HISTORY_DAY_CARE,:0.0

RESIDENCY_HISTORY_DAY_CARE_TYPE,:0.0

RESIDENCY_HISTORY_DAY_CARE_MESSAGE1,:0.0

RESIDENCY_HISTORY_DAY_CARE_MESSAGE2,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_STREET_ADDRESS,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_STREET_ADDRESS_2,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_CITY,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_STATE,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_ZIP_CODE,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_TELEPHONE,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_SPECIFY_NAME,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_SPECIFY_ADDRESS,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_SPECIFY_CITY_STATE_ZIP,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_SPECIFY_PHONE,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_SPECIFY_FAX,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_SPECIFY_EMAIL,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_HOURS,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_CONDITION,:0.0

RESIDENCY_HISTORY_DAY_CARE_INFO_CONDITION_OTHER_SECIFY,:0.0

HAZARD_BEHAV_FINGERS,:0.0

HAZARD_BEHAV_MOUTH,:0.0

HAZARD_BEHAV_MOUTH_YES_SPECIFY,:0.0

HAZARD_BEHAV_CHEW,:0.0

HAZARD_BEHAV_CHEW_YES_SPECIFY,:0.0

HAZARD_BEHAV_GLAZE,:0.0

HAZARD_BEHAV_METAL,:0.0

HAZARD_BEHAV_METAL_YES_SPECIFY,:0.0

HAZARD_BEHAV_PAINT_CHIPS,:0.0

HAZARD_BEHAV_PAINT_CHIPS_YES_LOCATION,:0.0

HAZARD_BEHAV_PLAY_AREA,:0.0

HAZARD_BEHAV_PRINTED,:0.0

HAZARD_BEHAV_COSMETICS,:0.0

HAZARD_BEHAV_COSMETICS_YES_FOREIGN,:0.0

HAZARD_BEHAV_CUP,:0.0

HAZARD_BEHAV_CUP_YES_HANDMADE,:0.0

HAZARD_BEHAV_UTENSIL,:0.0

HAZARD_BEHAV_UTENSIL_YES_HANDMADE,:0.0

HAZARD_BEHAV_WICK,:0.0

HAZARD_BEHAV_PET,:0.0

HAZARD_BEHAV_HAND_MOUTH,:0.0

HAZARD_BEHAV_HAND_MOUTH_YES_SPECIFY,:0.0

HAZARD_BEHAV_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

HAZARD_BEHAV_ASSESSMENT_MSG,:0.0

HAZARD_BEHAV_ASSESSMENT_HAND,:0.0

HAZARD_BEHAV_ASSESSMENT_MOUTHING,:0.0

HAZARD_BEHAV_ASSESSMENT_MOUTHING_YES_SPECIFY,:0.0

HAZARD_BEHAV_ASSESSMENT_OTHER,:0.0

HAZARD_BEHAV_ASSESSMENT_OTHER_YES_SPECIFY,:0.0

HAZARD_BEHAV_ASSESSMENT_ACTION_MSG,:0.0

HAZARD_BEHAV_ASSESSMENT_ACTION_COUNSELED,:0.0

HAZARD_BEHAV_ASSESSMENT_ACTION_COUNSELED_YES_SPECIFY,:0.0

HAZARD_BEHAV_ASSESSMENT_ACTION_OTHER_SPECIFY,:0.0

HAZARD_PAINT_PLAY,:0.0

HAZARD_PAINT_PLAY_CONDITION,:0.0

HAZARD_PAINT_PLAY_CONDITION_LOCATION,:0.0

HAZARD_PAINT_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

HAZARD_PAINT_ASSESSMENT_MSG,:0.0

HAZARD_PAINT_ASSESSMENT,:0.0

HAZARD_PAINT_ASSESSMENT_YES_SPECIFY,:0.0

HAZARD_PAINT_ASSESSMENT_DUST,:0.0

HAZARD_PAINT_ASSESSMENT_DUST_YES_SPECIFY,:0.0

HAZARD_PAINT_ASSESSMENT_ACTION_MSG,:0.0

HAZARD_PAINT_ASSESSMENT_ACTION,:0.0

HAZARD_PAINT_ASSESSMENT_ACTION_NO_WHY_NOT,:0.0

HAZARD_PAINT_ASSESSMENT_ACTION_NO_WHY_NOT_OTHER_SPECIFY,:0.0

HAZARD_WATER_SOURCE,:0.0

HAZARD_WATER_FAUCETS,:0.0

HAZARD_WATER_IMMEDIATELY,:0.0

HAZARD_WATER_TAP,:0.0

HAZARD_WATER_TAP_YES_HOT_COLD,:0.0

HAZARD_WATER_TAP_NO_SOURCE,:0.0

HAZARD_WATER_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

HAZARD_WATER_ASSESSMENT_MSG,:0.0

HAZARD_WATER_ASSESSMENT,:0.0

HAZARD_WATER_ASSESSMENT_ACTION_MSG,:0.0

HAZARD_WATER_ACTION_SAMPLES,:0.0

HAZARD_WATER_ACTION_SAMPLES_DATE,:0.0

HAZARD_WATER_ACTION_COUNSELED,:0.0

HAZARD_WATER_ACTION_COUNSELED_SPECIFIY,:0.0

HAZARD_SOIL_PLAY,:0.0

HAZARD_SOIL_GROUND_COVER,:0.0

HAZARD_SOIL_GROUND_COVER_LOCATION,:0.0

HAZARD_SOIL_GROUND_COVER_TYPE,:0.0

HAZARD_SOIL_PAINT_CHIPS,:0.0

HAZARD_SOIL_PAINT_CHIP_YES_LOCATION,:0.0

HAZARD_SOIL_HOUSE_CONSTRUCTION,:0.0

HAZARD_SOIL_HOUSE_CONSTRUCTION_LOCATION,:0.0

HAZARD_SOIL_HOUSE_CONSTRUCTION_TIME,:0.0

HAZARD_SOIL_HOUSE_CONSTRUCTION_END,:0.0

HAZARD_SOIL_NEIGHBOR_CONSTRUCTION,:0.0

HAZARD_SOIL_NEIGHBOR_CONSTRUCTION_TIME,:0.0

HAZARD_SOIL_NEIGHBOR_CONSTRUCTION_END,:0.0

HAZARD_SOIL_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

HAZARD_SOIL_ASSESSMENT_MSG,:0.0

HAZARD_SOIL_ASSESSMENT,:0.0

HAZARD_SOIL_ASSESSMENT_ACTION_MSG,:0.0

HAZARD_SOIL_ACTION_SAMPLES,:0.0

HAZARD_SOIL_ACTION_SAMPLES_NO_WHY,:0.0

HAZARD_SOIL_ACTION_SAMPLES_NO_WHY_SPECIFY,:0.0

HAZARD_SOIL_ACTION_COUNSELED,:0.0

HAZARD_SOIL_ACTION_COUNSELED_YES_DATE,:0.0

HAZARD_SOIL_ACTION_COUNSELED_NO_WHY,:0.0

HAZARD_SOIL_ACTION_COUNSELED_NO_WHY_OTHER_SPECIFY,:0.0

HAZARD_OTHER_COSMETICS,:0.0

HAZARD_OTHER_COSMETICS_YES_TYPE,:0.0

SAMPLE_RESULT,:0.0

HAZARD_OTHER_REMEDIES,:0.0

HAZARD_OTHER_REMEDIES_YES_TYPE,:0.0

REMEDIES_SAMPLE_POSITIVE,:0.0

HAZARD_OTHER_TOYS_RECALLED,:0.0

HAZARD_OTHER_BEVERAGE_CONTAINER,:0.0

HAZARD_OTHER_DISHES,:0.0

HAZARD_OTHER_FOOD_CONTAINER,:0.0

HAZARD_OTHER_FOOD_CONTAINER_GLAZED,:0.0

HAZARD_OTHER_FOOD_CONTAINER_CERAMIC,:0.0

HAZARD_OTHER_FOOD_CONTAINER_CERAMIC_YES_SPECIFY,:0.0

HAZARD_OTHER_FOOD_CONTAINER_CERAMIC_IMPORTED,:0.0

HAZARD_OTHER_IMPORTER_CANNED_FOOD,:0.0

HAZARD_OTHER_MINI_BLINDS,:0.0

HAZARD_OTHER_FISHING_SINKERS,:0.0

HAZARD_OTHER_FISHING_SINKERS_RELATIONSHIP,:0.0

HAZARD_OTHER_FISHING_SINKERS_RELATIONSHIP_OTHER,:0.0

HAZARD_OTHER_FISHING_SINKERS_LOCATION,:0.0

HAZARD_OTHER_MATTERIALS,:0.0

HAZARD_OTHER_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

HAZARD_OTHER_ASSESSMENT_MSG,:0.0

HAZARD_OTHER_ASSESSMENT_EXPOSURE,:0.0

HAZARD_OTHER_ASSESSMENT_ACTION_MSG,:0.0

HAZARD_OTHER_ACTION_COUNSEL,:0.0

HAZARD_OTHER_ASSESSMENT_ACTION_OTHER,:0.0

HOUSE_KEEPING_CLEANING,:0.0

HOUSE_KEEPING_CLEANING_HOW_OFTEN,:0.0

HOUSE_KEEPING_CLEANING_HOW_OFTEN_SWEEP,:0.0

HOUSE_KEEPING_CLEANING_HOW_OFTEN_MOP,:0.0

HOUSE_KEEPING_CLEANING_HOW_OFTEN_VACUUM,:0.0

HOUSE_KEEPING_CLEANING_HOW_OFTEN_WINDOW,:0.0

HOUSE_KEEPING_FLOOR,:0.0

HOUSE_KEEPING_CLEANING_FLOOR_SPECIFY,:0.0

HOUSE_KEEPING_CLEANING_FLOOR_SPECIFY_OTHER_SPECIFY,:0.0

HOUSE_KEEPING_OVERALL,:0.0

HOUSE_KEEPING_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

HOUSE_KEEPING_ASSESSMENT_MSG,:0.0

HOUSE_KEEPING_ASSESSMENT_CLEANING,:0.0

HOUSE_KEEPING_ASSESSMENT_FLOOR,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_MSG,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_COUNSELED,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_COUNSELED_CLEANING,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_COUNSELED_CLEANING_YES_SPECIFY,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_INSTRUCTED_CLEANING,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_INSTRUCTED_CLEANING_YES_SPECIFY,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_FLOORING,:0.0

HOUSE_KEEPING_ASSESSMENT_ACTION_FLOORING_YES_SPECIFY,:0.0

ACTIVITIES_FAMILY_RISK,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_OTHER,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_TYPE,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_TYPE_OTHER,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_EXPOSURE_TYPE,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_FIRST_NAME,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_LAST_NAME,:0.0

ACTIVITIES_FAMILY_RISK_MEMBER_LOCATION,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED_WHO,:0.0

ACTIVITIES_FAMILY_TESTED_WHO_OTHER,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED_BLL,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED_DATE,:0.0

ACTIVITIES_FAMILY_LEAD_TESTED_SIBLINGS,:0.0

OCCUPATIONAL_CLOTHES,:0.0

OCCUPATIONAL_VEHICLE,:0.0

OCCUPATIONAL_HOME_EXPOSURE,:0.0

OCCUPATIONAL_ASSESSMENTS_AND_ACTIONS_DETAILS,:0.0

OCCUPATIONAL_ASSESSMENT_MSG,:0.0

OCCUPATIONAL_ASSESSMENT_EXPOSURE_WORK,:0.0

OCCUPATIONAL_ASSESSMENT_EXPOSURE_HOBBY,:0.0

OCCUPATIONAL_ACTIONS_MSG,:0.0

OCCUPATIONAL_ACTIONS_HOBBY,:0.0

OCCUPATIONAL_ACTIONS_ADULT_TESTING,:0.0

OCCUPATIONAL_ACTION_COUNSEL,:0.0

INTERIM_DATE,INTERIM_DATE:1.0000001

INTERIM_MEASURES_IMPLEMENTED,INTERIM_MEASURES_IMPLEMENTED:0.99999994

INTERIM_MEASURESIMPLEMENTED_OTHER,INTERIM_MEASURESIMPLEMENTED_OTHER:1.0000002

INTERIM_MEASURES_IMPLEMENTED_FIRST_NAME,INTERIM_MEASURES_IMPLEMENTED_FIRST_NAME:0.9999999

INTERIM_MEASURES_IMPLEMENTED_LAST_NAME,INTERIM_MEASURES_IMPLEMENTED_LAST_NAME:1.0000001

INTERIM_MEASURES_IMPLEMENTED_PHONE,INTERIM_MEASURES_IMPLEMENTED_PHONE:1.0

INTERIM_RELOCATION,INTERIM_RELOCATION:1.0

INTERIM_RELOCATION_DATE,INTERIM_RELOCATION_DATE:1.0000001

INTERIM_RELOCATION_ADDRESS,INTERIM_RELOCATION_ADDRESS_STATE:0.95718086

INTERIM_RELOCATION_ADDRESS_STREET,INTERIM_RELOCATION_ADDRESS_STREET:1.0000001

INTERIM_RELOCATION_ADDRESS_CITY,INTERIM_RELOCATION_ADDRESS_CITY:1.0000001

INTERIM_RELOCATION_ADDRESS_STATE,INTERIM_RELOCATION_ADDRESS_STATE:1.0000002

INTERIM_RELOCATION_ADDRESS_ZIP,INTERIM_RELOCATION_ADDRESS_ZIP:1.0

INTERIM_RELOCATION_MEASURES,INTERIM_RELOCATION_MEASURES:0.99999994

INTERIM_RELOCATION_MEASURES_OTHER,INTERIM_RELOCATION_MEASURES_OTHER:1.0000002

INTERIM_ABATEMENT_RELOCATION,INTERIM_ABATEMENT_RELOCATION:1.0000002

INTERIM_ABATEMENT_RELOCATION_YES_DATE,INTERIM_ABATEMENT_RELOCATION_YES_DATE:1.0000004

INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS,INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STATE:0.9643624

INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STREET,INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STREET:1.0000002

INTERIM_ABATEMENT_RELOCATION_YES_CITY,INTERIM_ABATEMENT_RELOCATION_YES_CITY:1.0000002

INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STATE,INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_STATE:1.0000002

INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_ZIP,INTERIM_ABATEMENT_RELOCATION_YES_ADDRESS_ZIP:1.0000004

INTERIM_ABATEMENT_RELOCATION_YES_MEASURES,INTERIM_ABATEMENT_RELOCATION_YES_MEASURES:0.9999999

INTERIM_ABATEMENT_RELOCATION_YES_MEASURES_OTHER,INTERIM_ABATEMENT_RELOCATION_YES_MEASURES_OTHER:1.0000001

INTERIM_ABATEMENT_NO_RELOCATION,INTERIM_ABATEMENT_NO_RELOCATION:0.99999976

INTERIM_ABATEMENT_NO_RELOCATION_MEASURES,INTERIM_ABATEMENT_NO_RELOCATION_MEASURES:1.0

INTER_ABATEMENT_NO_RELOCATION_MEASURES_OTHER,INTER_ABATEMENT_NO_RELOCATION_MEASURES_OTHER:1.0

REFERRALS_INFORMATION,REFERRALS_INFORMATION:1.0000001

REFERRALS_INFORMATION_YES_DATE,REFERRALS_INFORMATION_YES_DATE:1.0000002

REFERRALS_INFORMATION_YES_SPECIFY,REFERRALS_INFORMATION_YES_SPECIFY:1.0

REFERRALS,REFERRALS:1.0000001

REFERRALS_DSS_YES_DATE,REFERRALS_DSS_YES_DATE:0.9999999

REFERRALS_DSS_YES_ACTIONS,REFERRALS_DSS_YES_ACTIONS:1.0

WIC_REFERRAL_DETAILS,REFERRALS_WIC_REFERRAL:0.925615

REFERRALS_WIC_MESSAGE,:0.0

REFERRALS_WIC_REFERRAL,REFERRALS_WIC_REFERRAL:1.0

EARLY_HEAD_START_HEAD_START_DETAILS,:0.0

REFERRALS_HEAD_START_MESSAGE,:0.0

REFERRALS_HEAD_START_REFERRAL,REFERRALS_HEAD_START_REFERRAL:1.0000001

NON_INSURED_UNDER_INSURED_QUEST_DETAILS,:0.0

NON_INSURED_UNDER_INSURED_QUEST_MESSAGE,:0.0

NON_INSURED_UNDER_INSURED_QUEST_REFERRAL,NON_INSURED_UNDER_INSURED_QUEST_REFERRAL:1.0

BIRTH_TO_THREE_DETAILS,:0.0

REFERRAL_BIRTH_TO_THREE,REFERRAL_BIRTH_TO_THREE_REFERRAL:0.9437541

REFERRAL_BIRTH_TO_THREE_REFERRAL,REFERRAL_BIRTH_TO_THREE_REFERRAL:1.0000001

REFERRAL_BIRTH_TO_THREE_REFERRAL_YES_MESSAGE,:0.0

MISC_DETAILS,:0.0

REFERRAL_ABATEMENT,REFERRAL_ABATEMENT:1.0

REFERRAL_ABATEMENT_YES_DATE,REFERRAL_ABATEMENT_YES_DATE:0.99999994

REFERRAL_ABATEMENT_YES_SOURCE,REFERRAL_ABATEMENT_YES_SOURCE:1.0000004

ADULT_EVENT_DATE,:0.0

PERSON_IDENTIFIER,:0.0

STATE_REP,:0.0

CLASSIFICATION_STATUS,:0.0

REPORT_TO_CDC,:0.0

STATE_CASE_NUMBER,:0.0

DATE_TRANSMITTED_CDC,:0.0

MMWR_WEEK,:0.0

LAB_REVIEW_REQUIRED_LOCAL,:0.0

LAB_REVIEW_DATE_LOCAL,:0.0

LAB_REVIEW_REQUIRED_STATE,:0.0

LAB_REVIEW_DATE_STATE,:0.0

BLOOD_DRAW_DATE,:0.0

BLOOD_DRAW_DATE_TYPE,:0.0

COLLECTION_METHOD,:0.0

BLL,:0.0

RESULT_RECEIVED_DATE,:0.0

SPECIMEN_ID,:0.0

LAB_REPORTER,:0.0

LAB_CLIENT,:0.0

CONTACT,:0.0

PHYSICIAN_ADDRESS,:0.0

PHYSICIAN_PHONE,:0.0

FOLLOW_UP_REQUIRED,:0.0

FOLLOW_UP_REQUIRED_DATE,:0.0

TITLE,:0.0

FIRST_NAME,:0.0

MIDDLE_NAME,:0.0

LAST_NAME,:0.0

DOB,:0.0

AGE_YEARS,:0.0

GENDER,:0.0

ADULT_RACE,:0.0

RACE_AMERICAN_INDIAN_ALASKAN_NATIVE_DETAIL,:0.0

RACE_ASIAN_DETAIL,:0.0

RACE_BLACK_AFRICAN_AMERICAN_DETAIL,:0.0

RACE_NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DETAIL,:0.0

RACE_WHITE_DETAIL,:0.0

ADULT_RACE_OTHER_SPECIFY,:0.0

ADULT_HISPANIC,:0.0

TELEPHONE_HOME,:0.0

TELEPHONE_CELL,:0.0

TELEPHONE_WORK,:0.0

SOCIAL_SECURITY_NUMBER,:0.0

STREET_ADDRESS,:0.0

STREET_ADDRESS_2,:0.0

CITY,[lead_res_city]City:1.0000001

STATE,:0.0

ADULT_CURRENT_ISLAND,:0.0

ZIP_CODE,[lead_6hr_zip]Zip Code:1.0

COUNTY,[lead_res_county]County:1.0000002

DECEASED,:0.0

STATE_EXP_KNOWN,:0.0

STATE_EXP,:0.0

COUNTY_EXP,:0.0

WORK_RELATED,:0.0

EMPLOYER,:0.0

OCCUPATION,[lead_adult_lead_industry_occ]Occupation:1.0

OCCUPATION_OTHER_DESC,:0.0

EMP_START_DATE,:0.0

EMP_END_DATE,:0.0

COMMENTS,:0.0

ADULT_NAICS,:0.0

ADULT_SIC,:0.0

ADULT_COC,:0.0

PROCESS,:0.0

PROCESS_OTHER_DESC,:0.0

ADULT_DATE_OF_CONTACT,:0.0

ADULT_DATE_OF_CONTACT_DATE_TYPE,:0.0

ADULT_DATE_OF_CONTACT_DATE_TYPE_OTHER_SPECIFY,:0.0

ADULT_DATE_OF_CONTACT_PERSON_CONTACTED,:0.0

ADULT_DATE_OF_CONTACT_DATE_METHOD,:0.0

ADULT_DATE_OF_CONTACT_DATE_METHOD_OTHER_SPECIFY,:0.0

ADULT_DATE_OF_CONTACT_REASON,:0.0

CASE_TYPE_HIDDEN,:0.0

SCHOOL_READINESS_READING,SCHOOL_READINESS_READING:0.99999976

SCHOOL_READINESS_PLAYING,SCHOOL_READINESS_PLAYING:1.0000001

SCHOOL_READINESS_MEDIA,SCHOOL_READINESS_MEDIA:0.99999976

SCHOOL_READINESS_DEVELOPMENT,SCHOOL_READINESS_DEVELOPMENT:1.0000002


In [276]:
df_filtered = pd.DataFrame(filtered)
print(len(df_filtered))
df_filtered.loc[:,'target_label'].value_counts(dropna=False)

606

target_label
                                                      432
DEVELOPMENTAL_SCREENING_EIGHT_TWELVE_COMMUNICATION      8
DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_GROSS_MOTOR      7
DEVELOPMENTAL_SCREENING_SIXTEEN_TWENTY_FINE_MOTOR       4
DEVELOPMENTAL_SCREENING_FIFTYFOUR_SIXTY_FINE_MOTOR      3
                                                     ...
INTERIM_RELOCATION_ADDRESS_STREET                       1
INTERIM_RELOCATION_DATE                                 1
INTERIM_RELOCATION                                      1
INTERIM_MEASURES_IMPLEMENTED_PHONE                      1
CHECKLIST_INVESTIGATION_DATE                            1
Name: count, Length: 145, dtype: int64

In [277]:
# Merge df_filtered with df_origami, first set df_origami to original labels
df_origami.Label = original_labels

In [278]:
df_merge = pd.merge(df_filtered,df_origami,left_on='target_label',right_on='Label',how='left')

In [279]:
df_merge

                        Question target_label Field Label
0              ANY_OVER_5_OUTPUT                NaN   NaN
1       VENOUS_CONFIRMED_DISPLAY                NaN   NaN
2    MAX_VENOUS_BLL_RANGE_OUTPUT                NaN   NaN
3          MAX_VENOUS_BLL_OUTPUT                NaN   NaN
4     MAX_VENOUS_BLL_DATE_OUTPUT                NaN   NaN
..                           ...          ...   ...   ...
601         DR_OVERDUE_TEST_DATE                NaN   NaN
602           DR_MAILING_ADDRESS                NaN   NaN
603              DR_MAILING_CITY                NaN   NaN
604             DR_MAILING_STATE                NaN   NaN
605           DR_MAILING_ZIPCODE                NaN   NaN

[606 rows x 4 columns]

In [280]:
# merge the above merged df with output dataframe
df_final = pd.merge(df_output,df_merge,on='Question')
df_final

,Model,depth,Question,Message,mmg_element,cste_element,target_label,Field,Label
0,Childhood Lead,0,ANY_OVER_5_OUTPUT,,,,,NaN,NaN
1,Childhood Lead,0,VENOUS_CONFIRMED_DISPLAY,,,,,NaN,NaN
2,Childhood Lead,0,MAX_VENOUS_BLL_RANGE_OUTPUT,,,,,NaN,NaN
3,Childhood Lead,0,MAX_VENOUS_BLL_OUTPUT,,,,,NaN,NaN
4,Childhood Lead,0,MAX_VENOUS_BLL_DATE_OUTPUT,,,,,NaN,NaN
...,...,...,...,...,...,...,...,...,...
601,Childhood Lead,0,DR_OVERDUE_TEST_DATE,,,,,NaN,NaN
602,Childhood Lead,0,DR_MAILING_ADDRESS,,,,,NaN,NaN
603,Childhood Lead,0,DR_MAILING_CITY,,,,,NaN,NaN
604,Childhood Lead,0,DR_MAILING_STATE,,,,,NaN,NaN
605,Childhood Lead,0,DR_MAILING_ZIPCODE,,,,,NaN,NaN

In [281]:
# Add, rename, remove columns as needed
df_final['target_table'] = 'Custom__CaseLead'
df_final=df_final.rename(columns={'Field':'target_field'})
df_final=df_final.drop('Label',axis=1)

In [282]:
df_final = df_final[["Model",'Question','target_table','target_field','target_label','mmg_element','cste_element','Message','depth']]
df_final

,Model,Question,target_table,target_field,target_label,mmg_element,cste_element,Message,depth
0,Childhood Lead,ANY_OVER_5_OUTPUT,Custom__CaseLead,NaN,,,,,0
1,Childhood Lead,VENOUS_CONFIRMED_DISPLAY,Custom__CaseLead,NaN,,,,,0
2,Childhood Lead,MAX_VENOUS_BLL_RANGE_OUTPUT,Custom__CaseLead,NaN,,,,,0
3,Childhood Lead,MAX_VENOUS_BLL_OUTPUT,Custom__CaseLead,NaN,,,,,0
4,Childhood Lead,MAX_VENOUS_BLL_DATE_OUTPUT,Custom__CaseLead,NaN,,,,,0
...,...,...,...,...,...,...,...,...,...
601,Childhood Lead,DR_OVERDUE_TEST_DATE,Custom__CaseLead,NaN,,,,,0
602,Childhood Lead,DR_MAILING_ADDRESS,Custom__CaseLead,NaN,,,,,0
603,Childhood Lead,DR_MAILING_CITY,Custom__CaseLead,NaN,,,,,0
604,Childhood Lead,DR_MAILING_STATE,Custom__CaseLead,NaN,,,,,0
605,Childhood Lead,DR_MAILING_ZIPCODE,Custom__CaseLead,NaN,,,,,0

In [283]:
df_final[df_final['target_field'].isna()]

,Model,Question,target_table,target_field,target_label,mmg_element,cste_element,Message,depth
0,Childhood Lead,ANY_OVER_5_OUTPUT,Custom__CaseLead,NaN,,,,,0
1,Childhood Lead,VENOUS_CONFIRMED_DISPLAY,Custom__CaseLead,NaN,,,,,0
2,Childhood Lead,MAX_VENOUS_BLL_RANGE_OUTPUT,Custom__CaseLead,NaN,,,,,0
3,Childhood Lead,MAX_VENOUS_BLL_OUTPUT,Custom__CaseLead,NaN,,,,,0
4,Childhood Lead,MAX_VENOUS_BLL_DATE_OUTPUT,Custom__CaseLead,NaN,,,,,0
...,...,...,...,...,...,...,...,...,...
601,Childhood Lead,DR_OVERDUE_TEST_DATE,Custom__CaseLead,NaN,,,,,0
602,Childhood Lead,DR_MAILING_ADDRESS,Custom__CaseLead,NaN,,,,,0
603,Childhood Lead,DR_MAILING_CITY,Custom__CaseLead,NaN,,,,,0
604,Childhood Lead,DR_MAILING_STATE,Custom__CaseLead,NaN,,,,,0
605,Childhood Lead,DR_MAILING_ZIPCODE,Custom__CaseLead,NaN,,,,,0

In [284]:
df_final.to_csv('output/maven_lead_origami_similarity_match.csv',index=False)