In [82]:
# Code to do some analysis for questions under each Maven model requested by Jlo

In [83]:
import pandas as pd

In [84]:
df_maven = pd.read_csv('input/questions_by_model.csv',na_filter=False)
len(df_maven)

15006

In [85]:
df_maven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15006 entries, 0 to 15005
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   value             15006 non-null  object
 1   QUESTION_ID       15006 non-null  object
 2   question_package  15006 non-null  object
 3   MODEL_NAME        15006 non-null  object
dtypes: object(4)
memory usage: 469.1+ KB

In [86]:
def join_all_except_last(question,answer):

    # Check if answer matches last part of the question
    start=len(question)-len(answer)
    if(question[start:]==answer):
        return question[:start].strip('_')
    else:
        return question

In [87]:
df_maven.loc[:,'parent_question_id']  = [ join_all_except_last(q,a) for q,a in zip(df_maven.loc[:,'QUESTION_ID'],df_maven.loc[:,'value'])]

In [88]:
df_maven

,value,QUESTION_ID,question_package,MODEL_NAME,parent_question_id
0,NO,ABXCHEST_YN_NO,CLINICAL,DiseaseSurveillanceModel_General,ABXCHEST_YN
1,YES,ABXCHEST_YN_YES,CLINICAL,DiseaseSurveillanceModel_General,ABXCHEST_YN
2,12/31/2020,ACCOUNT_EMAIL_SENT_DATE,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel,ACCOUNT_EMAIL_SENT_DATE
3,NO,ACF_ABNORMAL_PUPILS_NO,CLINICAL,DiseaseSurveillanceModel_General,ACF_ABNORMAL_PUPILS
4,Oriented x1,ACF_ALTERED_MENTAL_STATUS_EXAM_ABNORMAL_DESC,CLINICAL,DiseaseSurveillanceModel_General,ACF_ALTERED_MENTAL_STATUS_EXAM_ABNORMAL_DESC
...,...,...,...,...,...
15001,YES,WIC_MOM_PREGANCY_YES,DEMOGRAPHICS,Childhood_Lead_Child_Model,WIC_MOM_PREGANCY
15002,Yuka Kawakami,WORK_AT_FOOD_PLACE_CONTACT,RISK_HISTORY,DiseaseSurveillanceModel_Hep,WORK_AT_FOOD_PLACE_CONTACT
15003,YES,WORK_PUBLIC_RESTRICTIONS_9_DAYS_SWELLING_YES,CONTROL_ISO_QUAR,DiseaseSurveillanceModel_General,WORK_PUBLIC_RESTRICTIONS_9_DAYS_SWELLING
15004,ZZZZZ,ZIP_CODE,REPORTING_MORBIDITY,DiseaseSurveillanceModel_STD,ZIP_CODE
15005,96815,ZIP_CODE,PATIENT_INFORMATION,EHRAndScreeningModel_STD,ZIP_CODE

In [89]:
# Group by parent_question_id and model_name to get the num of values reported in each group
# reset_index() to convert dataframegroupby object to dataframe
df_group = df_maven.groupby(by=['MODEL_NAME','parent_question_id']).count().reset_index()

In [90]:
df_group

,MODEL_NAME,parent_question_id,value,QUESTION_ID,question_package
0,Childhood_Lead_Child_Model,ACTIVITIES_FAMILY_LEAD_TESTED,2,2,2
1,Childhood_Lead_Child_Model,ACTIVITIES_FAMILY_LEAD_TESTED_BLL,1,1,1
2,Childhood_Lead_Child_Model,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,1,1,1
3,Childhood_Lead_Child_Model,ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME,1,1,1
4,Childhood_Lead_Child_Model,ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME,1,1,1
...,...,...,...,...,...
11150,PortalApplicationModel,STD_SCREENING_PARTNER,2,2,2
11151,PortalApplicationModel,STD_SCREENING_PARTNER_ID,1,1,1
11152,PortalApplicationModel,TYPE_OF_USER,2,2,2
11153,PortalApplicationModel,TYPE_OF_USER_STD,2,2,2
11154,PortalApplicationModel,USER_ACCOUNT_PROCESSED_BY,1,1,1

In [91]:
df_group[['MODEL_NAME','parent_question_id']].to_csv('output/model_and_parent_questions.csv',index=False)

In [92]:
# grouping again to get counts by model
df_group = df_group.groupby(by=['MODEL_NAME']).count().reset_index()

In [93]:
df_group

,MODEL_NAME,parent_question_id,value,QUESTION_ID,question_package
0,Childhood_Lead_Child_Model,386,386,386,386
1,Childhood_Lead_Investigation_Model,136,136,136,136
2,ClusterModel,207,207,207,207
3,DiseaseSurveillanceModel_AggNETSS,14,14,14,14
4,DiseaseSurveillanceModel_Coinfection,114,114,114,114
5,DiseaseSurveillanceModel_General,7477,7477,7477,7477
6,DiseaseSurveillanceModel_Hep,1388,1388,1388,1388
7,DiseaseSurveillanceModel_STD,1363,1363,1363,1363
8,EHRAndScreeningModel_STD,22,22,22,22
9,IsolationAndControlModel,7,7,7,7
10,PortalApplicationModel,41,41,41,41

In [94]:
df_group=df_group[['MODEL_NAME','parent_question_id']]

In [95]:
df_group

                              MODEL_NAME  parent_question_id
0             Childhood_Lead_Child_Model                 386
1     Childhood_Lead_Investigation_Model                 136
2                           ClusterModel                 207
3      DiseaseSurveillanceModel_AggNETSS                  14
4   DiseaseSurveillanceModel_Coinfection                 114
5       DiseaseSurveillanceModel_General                7477
6           DiseaseSurveillanceModel_Hep                1388
7           DiseaseSurveillanceModel_STD                1363
8               EHRAndScreeningModel_STD                  22
9               IsolationAndControlModel                   7
10                PortalApplicationModel                  41